// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertUser = `-- name: InsertUser :one
INSERT INTO users (id, name, email) VALUES ($1, $2, $3) RETURNING id
`

type InsertUserParams struct {
	ID    string
	Name  pgtype.Text
	Email pgtype.Text
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (string, error) {
	row := q.db.QueryRow(ctx, insertUser, arg.ID, arg.Name, arg.Email)
	var id string
	err := row.Scan(&id)
	return id, err
}
