// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: course.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addCourse = `-- name: AddCourse :one
INSERT INTO courses (title, description, completion_title, completion_message)
VALUES ($1, $2, $3, $4) RETURNING id
`

type AddCourseParams struct {
	Title             pgtype.Text
	Description       pgtype.Text
	CompletionTitle   pgtype.Text
	CompletionMessage pgtype.Text
}

func (q *Queries) AddCourse(ctx context.Context, arg AddCourseParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, addCourse,
		arg.Title,
		arg.Description,
		arg.CompletionTitle,
		arg.CompletionMessage,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteCourse = `-- name: DeleteCourse :exec
DELETE FROM courses WHERE id = $1
`

func (q *Queries) DeleteCourse(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCourse, id)
	return err
}

const deleteCourseMaterials = `-- name: DeleteCourseMaterials :exec
DELETE FROM course_materials WHERE id = ANY($1::uuid[])
`

func (q *Queries) DeleteCourseMaterials(ctx context.Context, dollar_1 []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCourseMaterials, dollar_1)
	return err
}

const deleteQuizAnswers = `-- name: DeleteQuizAnswers :exec
DELETE FROM quizanswers WHERE id = ANY($1::uuid[])
`

func (q *Queries) DeleteQuizAnswers(ctx context.Context, dollar_1 []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteQuizAnswers, dollar_1)
	return err
}

const deleteQuizQuestions = `-- name: DeleteQuizQuestions :exec
DELETE FROM quizquestions WHERE id = ANY($1::uuid[])
`

func (q *Queries) DeleteQuizQuestions(ctx context.Context, dollar_1 []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteQuizQuestions, dollar_1)
	return err
}

const deleteQuizSections = `-- name: DeleteQuizSections :exec
DELETE FROM quizsections WHERE id = ANY($1::uuid[])
`

func (q *Queries) DeleteQuizSections(ctx context.Context, dollar_1 []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteQuizSections, dollar_1)
	return err
}

const deleteVideoSections = `-- name: DeleteVideoSections :exec
DELETE FROM videosections WHERE id = ANY($1::uuid[])
`

func (q *Queries) DeleteVideoSections(ctx context.Context, dollar_1 []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteVideoSections, dollar_1)
	return err
}

const getAllCourses = `-- name: GetAllCourses :many
SELECT
  c.id,
  c.title,
  c.description,
  c.completion_title,
  c.completion_message,
  (
    SELECT json_agg(json_build_object(
      'id', v.id,
      'title', v.title,
      'storage_key', v.storage_key,
      'position', v.position
    ) ORDER BY v.position)
    FROM videosections v WHERE v.course_id = c.id
  ) AS video_sections,
  (
    SELECT json_agg(json_build_object(
      'id', q.id,
      'position', q.position
    ) ORDER BY q.position)
    FROM quizsections q WHERE q.course_id = c.id
  ) AS quiz_sections,
  (
    SELECT json_agg(json_build_object(
      'id', m.id,
      'name', m.name,
      'storage_key', m.storage_key,
      'position', m.position
    ) ORDER BY m.position)
    FROM course_materials m WHERE m.course_id = c.id
  ) AS materials
FROM courses c
ORDER BY c.title
`

type GetAllCoursesRow struct {
	ID                pgtype.UUID
	Title             pgtype.Text
	Description       pgtype.Text
	CompletionTitle   pgtype.Text
	CompletionMessage pgtype.Text
	VideoSections     []byte
	QuizSections      []byte
	Materials         []byte
}

func (q *Queries) GetAllCourses(ctx context.Context) ([]GetAllCoursesRow, error) {
	rows, err := q.db.Query(ctx, getAllCourses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllCoursesRow
	for rows.Next() {
		var i GetAllCoursesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.CompletionTitle,
			&i.CompletionMessage,
			&i.VideoSections,
			&i.QuizSections,
			&i.Materials,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAssignedCourseTitles = `-- name: GetAssignedCourseTitles :many
SELECT c.id, c.title, c.description
FROM courses c
INNER JOIN usercourses uc ON uc.course_id = c.id
WHERE uc.user_id = $1
ORDER BY c.title
`

type GetAssignedCourseTitlesRow struct {
	ID          pgtype.UUID
	Title       pgtype.Text
	Description pgtype.Text
}

func (q *Queries) GetAssignedCourseTitles(ctx context.Context, userID pgtype.Text) ([]GetAssignedCourseTitlesRow, error) {
	rows, err := q.db.Query(ctx, getAssignedCourseTitles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAssignedCourseTitlesRow
	for rows.Next() {
		var i GetAssignedCourseTitlesRow
		if err := rows.Scan(&i.ID, &i.Title, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCourse = `-- name: GetCourse :one
SELECT
  c.id,
  c.title,
  c.description,
  c.completion_title,
  c.completion_message,
  (
    SELECT json_agg(json_build_object(
      'id', v.id,
      'title', v.title,
      'storage_key', v.storage_key,
      'position', v.position
    ) ORDER BY v.position)
    FROM videosections v WHERE v.course_id = c.id
  ) AS video_sections,
  (
    SELECT json_agg(json_build_object(
      'id', qs.id,
      'position', qs.position,
      'questions', (
        SELECT json_agg(
          json_build_object(
            'id', qq.id,
            'question', qq.question,
            'position', qq.position,
            'is_multi_answer', qq.is_multi_answer,
            'answers', (
              SELECT json_agg(
                json_build_object(
                  'id', qa.id,
                  'answer', qa.answer,
                  'correct_answer', qa.correct_answer,
                  'position', qa.position
                ) ORDER BY qa.position
              )
              FROM quizanswers qa
              WHERE qa.quiz_question_id = qq.id
            )
          ) ORDER BY qq.position
        )
        FROM quizquestions qq
        WHERE qq.quiz_section_id = qs.id
      )
    ) ORDER BY qs.position)
    FROM quizsections qs WHERE qs.course_id = c.id
  ) AS quiz_sections,
  (
    SELECT json_agg(json_build_object(
      'id', m.id,
      'name', m.name,
      'storage_key', m.storage_key,
      'position', m.position
    ) ORDER BY m.position)
    FROM course_materials m WHERE m.course_id = c.id
  ) AS materials
FROM courses c
WHERE c.id = $1
`

type GetCourseRow struct {
	ID                pgtype.UUID
	Title             pgtype.Text
	Description       pgtype.Text
	CompletionTitle   pgtype.Text
	CompletionMessage pgtype.Text
	VideoSections     []byte
	QuizSections      []byte
	Materials         []byte
}

func (q *Queries) GetCourse(ctx context.Context, id pgtype.UUID) (GetCourseRow, error) {
	row := q.db.QueryRow(ctx, getCourse, id)
	var i GetCourseRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CompletionTitle,
		&i.CompletionMessage,
		&i.VideoSections,
		&i.QuizSections,
		&i.Materials,
	)
	return i, err
}

const getCourseMaterials = `-- name: GetCourseMaterials :many
SELECT
  id, name, position, storage_key
FROM course_materials
WHERE course_id = $1
ORDER BY position
`

type GetCourseMaterialsRow struct {
	ID         pgtype.UUID
	Name       string
	Position   pgtype.Int4
	StorageKey pgtype.UUID
}

func (q *Queries) GetCourseMaterials(ctx context.Context, courseID pgtype.UUID) ([]GetCourseMaterialsRow, error) {
	rows, err := q.db.Query(ctx, getCourseMaterials, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCourseMaterialsRow
	for rows.Next() {
		var i GetCourseMaterialsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Position,
			&i.StorageKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCourseQuizSections = `-- name: GetCourseQuizSections :many
SELECT
  qs.id,
  qs.position,
  qs.course_id,
  json_agg(
    json_build_object(
      'id', qq.id,
      'question', qq.question,
      'position', qq.position,
      'is_multi_answer', qq.is_multi_answer,
      'answers', (
        SELECT json_agg(
          json_build_object(
            'id', qa.id,
            'answer', qa.answer,
            'correct_answer', qa.correct_answer,
            'position', qa.position
          ) ORDER BY qa.position
        )
        FROM quizanswers qa
        WHERE qa.quiz_question_id = qq.id
      )
    ) ORDER BY qq.position
  ) AS questions
FROM quizsections qs
LEFT JOIN quizquestions qq ON qq.quiz_section_id = qs.id
WHERE qs.course_id = $1
GROUP BY qs.id, qs.position, qs.course_id
ORDER BY qs.position
`

type GetCourseQuizSectionsRow struct {
	ID        pgtype.UUID
	Position  pgtype.Int4
	CourseID  pgtype.UUID
	Questions []byte
}

func (q *Queries) GetCourseQuizSections(ctx context.Context, courseID pgtype.UUID) ([]GetCourseQuizSectionsRow, error) {
	rows, err := q.db.Query(ctx, getCourseQuizSections, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCourseQuizSectionsRow
	for rows.Next() {
		var i GetCourseQuizSectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Position,
			&i.CourseID,
			&i.Questions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCourseVideoSections = `-- name: GetCourseVideoSections :many
SELECT
  id, title, position, storage_key
FROM videosections
WHERE course_id = $1
ORDER BY position
`

type GetCourseVideoSectionsRow struct {
	ID         pgtype.UUID
	Title      pgtype.Text
	Position   pgtype.Int4
	StorageKey pgtype.UUID
}

func (q *Queries) GetCourseVideoSections(ctx context.Context, courseID pgtype.UUID) ([]GetCourseVideoSectionsRow, error) {
	rows, err := q.db.Query(ctx, getCourseVideoSections, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCourseVideoSectionsRow
	for rows.Next() {
		var i GetCourseVideoSectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Position,
			&i.StorageKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCoursesOverview = `-- name: GetCoursesOverview :many
SELECT id, title, description FROM courses ORDER BY title
`

type GetCoursesOverviewRow struct {
	ID          pgtype.UUID
	Title       pgtype.Text
	Description pgtype.Text
}

func (q *Queries) GetCoursesOverview(ctx context.Context) ([]GetCoursesOverviewRow, error) {
	rows, err := q.db.Query(ctx, getCoursesOverview)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCoursesOverviewRow
	for rows.Next() {
		var i GetCoursesOverviewRow
		if err := rows.Scan(&i.ID, &i.Title, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCourseMaterial = `-- name: InsertCourseMaterial :exec
INSERT INTO course_materials (id, name, storage_key, position, course_id)
VALUES ($1, $2, $3, $4, $5)
`

type InsertCourseMaterialParams struct {
	ID         pgtype.UUID
	Name       string
	StorageKey pgtype.UUID
	Position   pgtype.Int4
	CourseID   pgtype.UUID
}

func (q *Queries) InsertCourseMaterial(ctx context.Context, arg InsertCourseMaterialParams) error {
	_, err := q.db.Exec(ctx, insertCourseMaterial,
		arg.ID,
		arg.Name,
		arg.StorageKey,
		arg.Position,
		arg.CourseID,
	)
	return err
}

const insertQuizAnswer = `-- name: InsertQuizAnswer :exec
INSERT INTO quizanswers (answer, correct_answer, position, quiz_question_id)
VALUES ($1, $2, $3, $4)
`

type InsertQuizAnswerParams struct {
	Answer         pgtype.Text
	CorrectAnswer  pgtype.Bool
	Position       pgtype.Int4
	QuizQuestionID pgtype.UUID
}

func (q *Queries) InsertQuizAnswer(ctx context.Context, arg InsertQuizAnswerParams) error {
	_, err := q.db.Exec(ctx, insertQuizAnswer,
		arg.Answer,
		arg.CorrectAnswer,
		arg.Position,
		arg.QuizQuestionID,
	)
	return err
}

const insertQuizQuestion = `-- name: InsertQuizQuestion :one
INSERT INTO quizquestions (question, position, is_multi_answer, quiz_section_id)
VALUES ($1, $2, $3, $4) RETURNING id
`

type InsertQuizQuestionParams struct {
	Question      pgtype.Text
	Position      pgtype.Int4
	IsMultiAnswer bool
	QuizSectionID pgtype.UUID
}

func (q *Queries) InsertQuizQuestion(ctx context.Context, arg InsertQuizQuestionParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertQuizQuestion,
		arg.Question,
		arg.Position,
		arg.IsMultiAnswer,
		arg.QuizSectionID,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const insertQuizSection = `-- name: InsertQuizSection :one
INSERT INTO quizsections (position, course_id) VALUES ($1, $2) RETURNING id
`

type InsertQuizSectionParams struct {
	Position pgtype.Int4
	CourseID pgtype.UUID
}

func (q *Queries) InsertQuizSection(ctx context.Context, arg InsertQuizSectionParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertQuizSection, arg.Position, arg.CourseID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const insertVideoSection = `-- name: InsertVideoSection :exec
INSERT INTO videosections (title, storage_key, position, course_id)
VALUES ($1, $2, $3, $4)
`

type InsertVideoSectionParams struct {
	Title      pgtype.Text
	StorageKey pgtype.UUID
	Position   pgtype.Int4
	CourseID   pgtype.UUID
}

func (q *Queries) InsertVideoSection(ctx context.Context, arg InsertVideoSectionParams) error {
	_, err := q.db.Exec(ctx, insertVideoSection,
		arg.Title,
		arg.StorageKey,
		arg.Position,
		arg.CourseID,
	)
	return err
}

const removeDeletedSectionsFromProgress = `-- name: RemoveDeletedSectionsFromProgress :exec
UPDATE userprogress
SET completed_section_ids = (
  SELECT COALESCE(array_agg(section_id), ARRAY[]::uuid[])
  FROM unnest(completed_section_ids) AS section_id
  WHERE section_id != ALL($1::uuid[])
)
WHERE completed_section_ids && $1::uuid[]
`

func (q *Queries) RemoveDeletedSectionsFromProgress(ctx context.Context, dollar_1 []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, removeDeletedSectionsFromProgress, dollar_1)
	return err
}

const updateCourse = `-- name: UpdateCourse :exec
UPDATE courses
SET title = $1, description = $2, completion_title = $3, completion_message = $4
WHERE id = $5
`

type UpdateCourseParams struct {
	Title             pgtype.Text
	Description       pgtype.Text
	CompletionTitle   pgtype.Text
	CompletionMessage pgtype.Text
	ID                pgtype.UUID
}

func (q *Queries) UpdateCourse(ctx context.Context, arg UpdateCourseParams) error {
	_, err := q.db.Exec(ctx, updateCourse,
		arg.Title,
		arg.Description,
		arg.CompletionTitle,
		arg.CompletionMessage,
		arg.ID,
	)
	return err
}

const updateQuizSectionPosition = `-- name: UpdateQuizSectionPosition :exec
UPDATE quizsections SET position = $1 WHERE id = $2
`

type UpdateQuizSectionPositionParams struct {
	Position pgtype.Int4
	ID       pgtype.UUID
}

func (q *Queries) UpdateQuizSectionPosition(ctx context.Context, arg UpdateQuizSectionPositionParams) error {
	_, err := q.db.Exec(ctx, updateQuizSectionPosition, arg.Position, arg.ID)
	return err
}

const updateVideoSection = `-- name: UpdateVideoSection :exec
UPDATE videosections SET title = $1, storage_key = $2, position = $3 WHERE id = $4
`

type UpdateVideoSectionParams struct {
	Title      pgtype.Text
	StorageKey pgtype.UUID
	Position   pgtype.Int4
	ID         pgtype.UUID
}

func (q *Queries) UpdateVideoSection(ctx context.Context, arg UpdateVideoSectionParams) error {
	_, err := q.db.Exec(ctx, updateVideoSection,
		arg.Title,
		arg.StorageKey,
		arg.Position,
		arg.ID,
	)
	return err
}

const upsertCourseMaterial = `-- name: UpsertCourseMaterial :exec
INSERT INTO course_materials (id, name, storage_key, position, course_id)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  storage_key = EXCLUDED.storage_key,
  position = EXCLUDED.position
`

type UpsertCourseMaterialParams struct {
	ID         pgtype.UUID
	Name       string
	StorageKey pgtype.UUID
	Position   pgtype.Int4
	CourseID   pgtype.UUID
}

func (q *Queries) UpsertCourseMaterial(ctx context.Context, arg UpsertCourseMaterialParams) error {
	_, err := q.db.Exec(ctx, upsertCourseMaterial,
		arg.ID,
		arg.Name,
		arg.StorageKey,
		arg.Position,
		arg.CourseID,
	)
	return err
}

const upsertQuizAnswer = `-- name: UpsertQuizAnswer :exec
INSERT INTO quizanswers (id, answer, correct_answer, position, quiz_question_id)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (id) DO UPDATE SET
  answer = EXCLUDED.answer,
  correct_answer = EXCLUDED.correct_answer,
  position = EXCLUDED.position
`

type UpsertQuizAnswerParams struct {
	ID             pgtype.UUID
	Answer         pgtype.Text
	CorrectAnswer  pgtype.Bool
	Position       pgtype.Int4
	QuizQuestionID pgtype.UUID
}

func (q *Queries) UpsertQuizAnswer(ctx context.Context, arg UpsertQuizAnswerParams) error {
	_, err := q.db.Exec(ctx, upsertQuizAnswer,
		arg.ID,
		arg.Answer,
		arg.CorrectAnswer,
		arg.Position,
		arg.QuizQuestionID,
	)
	return err
}

const upsertQuizQuestion = `-- name: UpsertQuizQuestion :exec
INSERT INTO quizquestions (id, question, position, is_multi_answer, quiz_section_id)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (id) DO UPDATE SET
  question = EXCLUDED.question,
  position = EXCLUDED.position,
  is_multi_answer = EXCLUDED.is_multi_answer
`

type UpsertQuizQuestionParams struct {
	ID            pgtype.UUID
	Question      pgtype.Text
	Position      pgtype.Int4
	IsMultiAnswer bool
	QuizSectionID pgtype.UUID
}

func (q *Queries) UpsertQuizQuestion(ctx context.Context, arg UpsertQuizQuestionParams) error {
	_, err := q.db.Exec(ctx, upsertQuizQuestion,
		arg.ID,
		arg.Question,
		arg.Position,
		arg.IsMultiAnswer,
		arg.QuizSectionID,
	)
	return err
}
