// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addFailedEmail = `-- name: AddFailedEmail :exec
INSERT INTO email_failures (error, template_params, template_name, email_name) VALUES ($1, $2, $3, $4)
`

type AddFailedEmailParams struct {
	Error          string
	TemplateParams []byte
	TemplateName   string
	EmailName      string
}

func (q *Queries) AddFailedEmail(ctx context.Context, arg AddFailedEmailParams) error {
	_, err := q.db.Exec(ctx, addFailedEmail,
		arg.Error,
		arg.TemplateParams,
		arg.TemplateName,
		arg.EmailName,
	)
	return err
}

const deleteFailedEmail = `-- name: DeleteFailedEmail :exec
DELETE FROM email_failures WHERE id = $1::uuid
`

func (q *Queries) DeleteFailedEmail(ctx context.Context, dollar_1 pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteFailedEmail, dollar_1)
	return err
}

const getFailedEmails = `-- name: GetFailedEmails :many
SELECT id, template_params, template_name, email_name, retries FROM email_failures WHERE retries > 0
`

type GetFailedEmailsRow struct {
	ID             pgtype.UUID
	TemplateParams []byte
	TemplateName   string
	EmailName      string
	Retries        int32
}

func (q *Queries) GetFailedEmails(ctx context.Context) ([]GetFailedEmailsRow, error) {
	rows, err := q.db.Query(ctx, getFailedEmails)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFailedEmailsRow
	for rows.Next() {
		var i GetFailedEmailsRow
		if err := rows.Scan(
			&i.ID,
			&i.TemplateParams,
			&i.TemplateName,
			&i.EmailName,
			&i.Retries,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFailedEmail = `-- name: UpdateFailedEmail :exec
UPDATE email_failures SET retries = $1, error = $2
`

type UpdateFailedEmailParams struct {
	Retries int32
	Error   string
}

func (q *Queries) UpdateFailedEmail(ctx context.Context, arg UpdateFailedEmailParams) error {
	_, err := q.db.Exec(ctx, updateFailedEmail, arg.Retries, arg.Error)
	return err
}
