// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email.sql

package sqlc

import (
	"context"
)

const setFailedEmail = `-- name: SetFailedEmail :exec
INSERT INTO email_failures (error, params) VALUES ($1, $2)
`

type SetFailedEmailParams struct {
	Error  string
	Params []byte
}

func (q *Queries) SetFailedEmail(ctx context.Context, arg SetFailedEmailParams) error {
	_, err := q.db.Exec(ctx, setFailedEmail, arg.Error, arg.Params)
	return err
}
