// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: enrolment.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const disenrolInCourse = `-- name: DisenrolInCourse :exec
DELETE FROM usercourses WHERE user_id = $1 AND course_id = $2
`

type DisenrolInCourseParams struct {
	UserID   pgtype.Text
	CourseID pgtype.UUID
}

func (q *Queries) DisenrolInCourse(ctx context.Context, arg DisenrolInCourseParams) error {
	_, err := q.db.Exec(ctx, disenrolInCourse, arg.UserID, arg.CourseID)
	return err
}

const enrolInCourse = `-- name: EnrolInCourse :exec
INSERT INTO usercourses (user_id, course_id) VALUES ($1, $2)
`

type EnrolInCourseParams struct {
	UserID   pgtype.Text
	CourseID pgtype.UUID
}

func (q *Queries) EnrolInCourse(ctx context.Context, arg EnrolInCourseParams) error {
	_, err := q.db.Exec(ctx, enrolInCourse, arg.UserID, arg.CourseID)
	return err
}

const isUserEnrolledInCourse = `-- name: IsUserEnrolledInCourse :one
SELECT EXISTS(SELECT 1 FROM usercourses WHERE user_id = $1 AND course_id = $2)
`

type IsUserEnrolledInCourseParams struct {
	UserID   pgtype.Text
	CourseID pgtype.UUID
}

func (q *Queries) IsUserEnrolledInCourse(ctx context.Context, arg IsUserEnrolledInCourseParams) (bool, error) {
	row := q.db.QueryRow(ctx, isUserEnrolledInCourse, arg.UserID, arg.CourseID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
