// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: enrolment.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const disenrolInCourse = `-- name: DisenrolInCourse :exec
DELETE FROM usercourses WHERE user_id = $1 AND course_id = $2
`

type DisenrolInCourseParams struct {
	UserID   pgtype.Text
	CourseID pgtype.UUID
}

func (q *Queries) DisenrolInCourse(ctx context.Context, arg DisenrolInCourseParams) error {
	_, err := q.db.Exec(ctx, disenrolInCourse, arg.UserID, arg.CourseID)
	return err
}

const enrolInCourse = `-- name: EnrolInCourse :exec
INSERT INTO usercourses (user_id, course_id) VALUES ($1, $2)
`

type EnrolInCourseParams struct {
	UserID   pgtype.Text
	CourseID pgtype.UUID
}

func (q *Queries) EnrolInCourse(ctx context.Context, arg EnrolInCourseParams) error {
	_, err := q.db.Exec(ctx, enrolInCourse, arg.UserID, arg.CourseID)
	return err
}

const getUsersAndAssignedCourses = `-- name: GetUsersAndAssignedCourses :many
SELECT
  u.id,
  u.name,
  u.email,
  json_agg(c.course_id) FILTER (WHERE c.course_id IS NOT NULL) AS course_ids
FROM users u
LEFT JOIN usercourses c ON u.id = c.user_id
GROUP BY u.id, u.name, u.email
ORDER BY u.name
`

type GetUsersAndAssignedCoursesRow struct {
	ID        string
	Name      pgtype.Text
	Email     pgtype.Text
	CourseIds []byte
}

func (q *Queries) GetUsersAndAssignedCourses(ctx context.Context) ([]GetUsersAndAssignedCoursesRow, error) {
	rows, err := q.db.Query(ctx, getUsersAndAssignedCourses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersAndAssignedCoursesRow
	for rows.Next() {
		var i GetUsersAndAssignedCoursesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.CourseIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isUserEnrolledInCourse = `-- name: IsUserEnrolledInCourse :one
SELECT EXISTS(SELECT 1 FROM usercourses WHERE user_id = $1 AND course_id = $2)
`

type IsUserEnrolledInCourseParams struct {
	UserID   pgtype.Text
	CourseID pgtype.UUID
}

func (q *Queries) IsUserEnrolledInCourse(ctx context.Context, arg IsUserEnrolledInCourseParams) (bool, error) {
	row := q.db.QueryRow(ctx, isUserEnrolledInCourse, arg.UserID, arg.CourseID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
