// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Course struct {
	ID                pgtype.UUID
	Title             pgtype.Text
	Description       pgtype.Text
	CompletionTitle   pgtype.Text
	CompletionMessage pgtype.Text
}

type CourseMaterial struct {
	ID         pgtype.UUID
	CourseID   pgtype.UUID
	StorageKey pgtype.UUID
	Name       string
	Position   pgtype.Int4
}

type Quizanswer struct {
	ID             pgtype.UUID
	Answer         pgtype.Text
	CorrectAnswer  pgtype.Bool
	QuizQuestionID pgtype.UUID
	Position       pgtype.Int4
}

type Quizquestion struct {
	ID            pgtype.UUID
	Question      pgtype.Text
	Position      pgtype.Int4
	QuizSectionID pgtype.UUID
}

type Quizsection struct {
	ID       pgtype.UUID
	Position pgtype.Int4
	CourseID pgtype.UUID
}

type User struct {
	ID    string
	Name  pgtype.Text
	Email pgtype.Text
}

type UserQuizState struct {
	ID        pgtype.UUID
	UserID    string
	QuizID    pgtype.UUID
	QuizState []byte
	Attempts  int32
}

type Usercourse struct {
	ID       pgtype.UUID
	UserID   pgtype.Text
	CourseID pgtype.UUID
}

type Userprogress struct {
	ID                  pgtype.UUID
	UserID              string
	CourseID            pgtype.UUID
	CompletedSectionIds []pgtype.UUID
	CompletedIntro      pgtype.Bool
	CompletedCourse     pgtype.Bool
}

type Videosection struct {
	ID         pgtype.UUID
	Title      pgtype.Text
	Position   pgtype.Int4
	StorageKey pgtype.UUID
	CourseID   pgtype.UUID
}
