// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCourseById = `-- name: GetCourseById :one
SELECT id, title, description FROM courses WHERE id = $1
`

func (q *Queries) GetCourseById(ctx context.Context, id pgtype.UUID) (Course, error) {
	row := q.db.QueryRow(ctx, getCourseById, id)
	var i Course
	err := row.Scan(&i.ID, &i.Title, &i.Description)
	return i, err
}
