// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addCourse = `-- name: AddCourse :one
INSERT INTO courses (title, description) VALUES ($1, $2) RETURNING id
`

type AddCourseParams struct {
	Title       pgtype.Text
	Description pgtype.Text
}

func (q *Queries) AddCourse(ctx context.Context, arg AddCourseParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, addCourse, arg.Title, arg.Description)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getCourseByID = `-- name: GetCourseByID :one
SELECT id, title, description FROM courses WHERE id = $1
`

type GetCourseByIDRow struct {
	ID          pgtype.UUID
	Title       pgtype.Text
	Description pgtype.Text
}

func (q *Queries) GetCourseByID(ctx context.Context, id pgtype.UUID) (GetCourseByIDRow, error) {
	row := q.db.QueryRow(ctx, getCourseByID, id)
	var i GetCourseByIDRow
	err := row.Scan(&i.ID, &i.Title, &i.Description)
	return i, err
}

const getProgressByID = `-- name: GetProgressByID :one
SELECT completed_intro, completed_section_ids FROM userprogress WHERE user_id = $1 AND course_id = $2
`

type GetProgressByIDParams struct {
	UserID   string
	CourseID pgtype.UUID
}

type GetProgressByIDRow struct {
	CompletedIntro      pgtype.Bool
	CompletedSectionIds []pgtype.UUID
}

func (q *Queries) GetProgressByID(ctx context.Context, arg GetProgressByIDParams) (GetProgressByIDRow, error) {
	row := q.db.QueryRow(ctx, getProgressByID, arg.UserID, arg.CourseID)
	var i GetProgressByIDRow
	err := row.Scan(&i.CompletedIntro, &i.CompletedSectionIds)
	return i, err
}
