// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUser = `-- name: GetUser :one
SELECT id, name, email FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(&i.ID, &i.Name, &i.Email)
	return i, err
}

const getUsersAndAssignedCourses = `-- name: GetUsersAndAssignedCourses :many
SELECT
  u.id,
  u.name,
  u.email,
  json_agg(c.course_id) FILTER (WHERE c.course_id IS NOT NULL) AS course_ids
FROM users u
LEFT JOIN usercourses c ON u.id = c.user_id
GROUP BY u.id, u.name, u.email
ORDER BY u.name
`

type GetUsersAndAssignedCoursesRow struct {
	ID        string
	Name      pgtype.Text
	Email     pgtype.Text
	CourseIds []byte
}

func (q *Queries) GetUsersAndAssignedCourses(ctx context.Context) ([]GetUsersAndAssignedCoursesRow, error) {
	rows, err := q.db.Query(ctx, getUsersAndAssignedCourses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersAndAssignedCoursesRow
	for rows.Next() {
		var i GetUsersAndAssignedCoursesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.CourseIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
