// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/supanova-rp/supanova-server/internal/handlers"
	"sync"
)

// Ensure, that AuthProviderMock does implement handlers.AuthProvider.
// If this is not the case, regenerate this file with moq.
var _ handlers.AuthProvider = &AuthProviderMock{}

// AuthProviderMock is a mock implementation of handlers.AuthProvider.
//
//	func TestSomethingThatUsesAuthProvider(t *testing.T) {
//
//		// make and configure a mocked handlers.AuthProvider
//		mockedAuthProvider := &AuthProviderMock{
//			CreateUserFunc: func(ctx context.Context, email string, password string, name string) (string, error) {
//				panic("mock out the CreateUser method")
//			},
//		}
//
//		// use mockedAuthProvider in code that requires handlers.AuthProvider
//		// and then make assertions.
//
//	}
type AuthProviderMock struct {
	// CreateUserFunc mocks the CreateUser method.
	CreateUserFunc func(ctx context.Context, email string, password string, name string) (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateUser holds details about calls to the CreateUser method.
		CreateUser []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Email is the email argument value.
			Email string
			// Password is the password argument value.
			Password string
			// Name is the name argument value.
			Name string
		}
	}
	lockCreateUser sync.RWMutex
}

// CreateUser calls CreateUserFunc.
func (mock *AuthProviderMock) CreateUser(ctx context.Context, email string, password string, name string) (string, error) {
	if mock.CreateUserFunc == nil {
		panic("AuthProviderMock.CreateUserFunc: method is nil but AuthProvider.CreateUser was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Email    string
		Password string
		Name     string
	}{
		Ctx:      ctx,
		Email:    email,
		Password: password,
		Name:     name,
	}
	mock.lockCreateUser.Lock()
	mock.calls.CreateUser = append(mock.calls.CreateUser, callInfo)
	mock.lockCreateUser.Unlock()
	return mock.CreateUserFunc(ctx, email, password, name)
}

// CreateUserCalls gets all the calls that were made to CreateUser.
// Check the length with:
//
//	len(mockedAuthProvider.CreateUserCalls())
func (mock *AuthProviderMock) CreateUserCalls() []struct {
	Ctx      context.Context
	Email    string
	Password string
	Name     string
} {
	var calls []struct {
		Ctx      context.Context
		Email    string
		Password string
		Name     string
	}
	mock.lockCreateUser.RLock()
	calls = mock.calls.CreateUser
	mock.lockCreateUser.RUnlock()
	return calls
}
