// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/supanova-rp/supanova-server/internal/domain"
	"github.com/supanova-rp/supanova-server/internal/store/sqlc"
	"sync"
)

// Ensure, that CourseRepositoryMock does implement domain.CourseRepository.
// If this is not the case, regenerate this file with moq.
var _ domain.CourseRepository = &CourseRepositoryMock{}

// CourseRepositoryMock is a mock implementation of domain.CourseRepository.
//
//	func TestSomethingThatUsesCourseRepository(t *testing.T) {
//
//		// make and configure a mocked domain.CourseRepository
//		mockedCourseRepository := &CourseRepositoryMock{
//			AddCourseFunc: func(contextMoqParam context.Context, addCourseParams sqlc.AddCourseParams) (*domain.Course, error) {
//				panic("mock out the AddCourse method")
//			},
//			GetCourseFunc: func(contextMoqParam context.Context, uUID pgtype.UUID) (*domain.Course, error) {
//				panic("mock out the GetCourse method")
//			},
//			GetCoursesOverviewFunc: func(contextMoqParam context.Context) ([]domain.CourseOverview, error) {
//				panic("mock out the GetCoursesOverview method")
//			},
//		}
//
//		// use mockedCourseRepository in code that requires domain.CourseRepository
//		// and then make assertions.
//
//	}
type CourseRepositoryMock struct {
	// AddCourseFunc mocks the AddCourse method.
	AddCourseFunc func(contextMoqParam context.Context, addCourseParams sqlc.AddCourseParams) (*domain.Course, error)

	// GetCourseFunc mocks the GetCourse method.
	GetCourseFunc func(contextMoqParam context.Context, uUID pgtype.UUID) (*domain.Course, error)

	// GetCoursesOverviewFunc mocks the GetCoursesOverview method.
	GetCoursesOverviewFunc func(contextMoqParam context.Context) ([]domain.CourseOverview, error)

	// calls tracks calls to the methods.
	calls struct {
		// AddCourse holds details about calls to the AddCourse method.
		AddCourse []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// AddCourseParams is the addCourseParams argument value.
			AddCourseParams sqlc.AddCourseParams
		}
		// GetCourse holds details about calls to the GetCourse method.
		GetCourse []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// UUID is the uUID argument value.
			UUID pgtype.UUID
		}
		// GetCoursesOverview holds details about calls to the GetCoursesOverview method.
		GetCoursesOverview []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
		}
	}
	lockAddCourse          sync.RWMutex
	lockGetCourse          sync.RWMutex
	lockGetCoursesOverview sync.RWMutex
}

// AddCourse calls AddCourseFunc.
func (mock *CourseRepositoryMock) AddCourse(contextMoqParam context.Context, addCourseParams sqlc.AddCourseParams) (*domain.Course, error) {
	if mock.AddCourseFunc == nil {
		panic("CourseRepositoryMock.AddCourseFunc: method is nil but CourseRepository.AddCourse was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		AddCourseParams sqlc.AddCourseParams
	}{
		ContextMoqParam: contextMoqParam,
		AddCourseParams: addCourseParams,
	}
	mock.lockAddCourse.Lock()
	mock.calls.AddCourse = append(mock.calls.AddCourse, callInfo)
	mock.lockAddCourse.Unlock()
	return mock.AddCourseFunc(contextMoqParam, addCourseParams)
}

// AddCourseCalls gets all the calls that were made to AddCourse.
// Check the length with:
//
//	len(mockedCourseRepository.AddCourseCalls())
func (mock *CourseRepositoryMock) AddCourseCalls() []struct {
	ContextMoqParam context.Context
	AddCourseParams sqlc.AddCourseParams
} {
	var calls []struct {
		ContextMoqParam context.Context
		AddCourseParams sqlc.AddCourseParams
	}
	mock.lockAddCourse.RLock()
	calls = mock.calls.AddCourse
	mock.lockAddCourse.RUnlock()
	return calls
}

// GetCourse calls GetCourseFunc.
func (mock *CourseRepositoryMock) GetCourse(contextMoqParam context.Context, uUID pgtype.UUID) (*domain.Course, error) {
	if mock.GetCourseFunc == nil {
		panic("CourseRepositoryMock.GetCourseFunc: method is nil but CourseRepository.GetCourse was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		UUID            pgtype.UUID
	}{
		ContextMoqParam: contextMoqParam,
		UUID:            uUID,
	}
	mock.lockGetCourse.Lock()
	mock.calls.GetCourse = append(mock.calls.GetCourse, callInfo)
	mock.lockGetCourse.Unlock()
	return mock.GetCourseFunc(contextMoqParam, uUID)
}

// GetCourseCalls gets all the calls that were made to GetCourse.
// Check the length with:
//
//	len(mockedCourseRepository.GetCourseCalls())
func (mock *CourseRepositoryMock) GetCourseCalls() []struct {
	ContextMoqParam context.Context
	UUID            pgtype.UUID
} {
	var calls []struct {
		ContextMoqParam context.Context
		UUID            pgtype.UUID
	}
	mock.lockGetCourse.RLock()
	calls = mock.calls.GetCourse
	mock.lockGetCourse.RUnlock()
	return calls
}

// GetCoursesOverview calls GetCoursesOverviewFunc.
func (mock *CourseRepositoryMock) GetCoursesOverview(contextMoqParam context.Context) ([]domain.CourseOverview, error) {
	if mock.GetCoursesOverviewFunc == nil {
		panic("CourseRepositoryMock.GetCoursesOverviewFunc: method is nil but CourseRepository.GetCoursesOverview was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
	}{
		ContextMoqParam: contextMoqParam,
	}
	mock.lockGetCoursesOverview.Lock()
	mock.calls.GetCoursesOverview = append(mock.calls.GetCoursesOverview, callInfo)
	mock.lockGetCoursesOverview.Unlock()
	return mock.GetCoursesOverviewFunc(contextMoqParam)
}

// GetCoursesOverviewCalls gets all the calls that were made to GetCoursesOverview.
// Check the length with:
//
//	len(mockedCourseRepository.GetCoursesOverviewCalls())
func (mock *CourseRepositoryMock) GetCoursesOverviewCalls() []struct {
	ContextMoqParam context.Context
} {
	var calls []struct {
		ContextMoqParam context.Context
	}
	mock.lockGetCoursesOverview.RLock()
	calls = mock.calls.GetCoursesOverview
	mock.lockGetCoursesOverview.RUnlock()
	return calls
}
