// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/supanova-rp/supanova-server/internal/domain"
	"sync"
)

// Ensure, that CourseRepositoryMock does implement domain.CourseRepository.
// If this is not the case, regenerate this file with moq.
var _ domain.CourseRepository = &CourseRepositoryMock{}

// CourseRepositoryMock is a mock implementation of domain.CourseRepository.
//
//	func TestSomethingThatUsesCourseRepository(t *testing.T) {
//
//		// make and configure a mocked domain.CourseRepository
//		mockedCourseRepository := &CourseRepositoryMock{
//			AddCourseFunc: func(contextMoqParam context.Context, addCourseParams *domain.AddCourseParams) (*domain.Course, error) {
//				panic("mock out the AddCourse method")
//			},
//			DeleteCourseFunc: func(contextMoqParam context.Context, uUID uuid.UUID) error {
//				panic("mock out the DeleteCourse method")
//			},
//			EditCourseFunc: func(contextMoqParam context.Context, editCourseParams *domain.EditCourseParams) (*domain.Course, error) {
//				panic("mock out the EditCourse method")
//			},
//			GetAllCoursesFunc: func(contextMoqParam context.Context) ([]*domain.AllCourseLegacy, error) {
//				panic("mock out the GetAllCourses method")
//			},
//			GetAssignedCourseTitlesFunc: func(contextMoqParam context.Context, s string) ([]domain.CourseOverview, error) {
//				panic("mock out the GetAssignedCourseTitles method")
//			},
//			GetCourseFunc: func(contextMoqParam context.Context, uUID pgtype.UUID) (*domain.Course, error) {
//				panic("mock out the GetCourse method")
//			},
//			GetCourseMaterialsFunc: func(contextMoqParam context.Context, uUID uuid.UUID) ([]domain.CourseMaterial, error) {
//				panic("mock out the GetCourseMaterials method")
//			},
//			GetCoursesOverviewFunc: func(contextMoqParam context.Context) ([]domain.CourseOverview, error) {
//				panic("mock out the GetCoursesOverview method")
//			},
//		}
//
//		// use mockedCourseRepository in code that requires domain.CourseRepository
//		// and then make assertions.
//
//	}
type CourseRepositoryMock struct {
	// AddCourseFunc mocks the AddCourse method.
	AddCourseFunc func(contextMoqParam context.Context, addCourseParams *domain.AddCourseParams) (*domain.Course, error)

	// DeleteCourseFunc mocks the DeleteCourse method.
	DeleteCourseFunc func(contextMoqParam context.Context, uUID uuid.UUID) error

	// EditCourseFunc mocks the EditCourse method.
	EditCourseFunc func(contextMoqParam context.Context, editCourseParams *domain.EditCourseParams) (*domain.Course, error)

	// GetAllCoursesFunc mocks the GetAllCourses method.
	GetAllCoursesFunc func(contextMoqParam context.Context) ([]*domain.AllCourseLegacy, error)

	// GetAssignedCourseTitlesFunc mocks the GetAssignedCourseTitles method.
	GetAssignedCourseTitlesFunc func(contextMoqParam context.Context, s string) ([]domain.CourseOverview, error)

	// GetCourseFunc mocks the GetCourse method.
	GetCourseFunc func(contextMoqParam context.Context, uUID pgtype.UUID) (*domain.Course, error)

	// GetCourseMaterialsFunc mocks the GetCourseMaterials method.
	GetCourseMaterialsFunc func(contextMoqParam context.Context, uUID uuid.UUID) ([]domain.CourseMaterial, error)

	// GetCoursesOverviewFunc mocks the GetCoursesOverview method.
	GetCoursesOverviewFunc func(contextMoqParam context.Context) ([]domain.CourseOverview, error)

	// calls tracks calls to the methods.
	calls struct {
		// AddCourse holds details about calls to the AddCourse method.
		AddCourse []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// AddCourseParams is the addCourseParams argument value.
			AddCourseParams *domain.AddCourseParams
		}
		// DeleteCourse holds details about calls to the DeleteCourse method.
		DeleteCourse []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// UUID is the uUID argument value.
			UUID uuid.UUID
		}
		// EditCourse holds details about calls to the EditCourse method.
		EditCourse []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// EditCourseParams is the editCourseParams argument value.
			EditCourseParams *domain.EditCourseParams
		}
		// GetAllCourses holds details about calls to the GetAllCourses method.
		GetAllCourses []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
		}
		// GetAssignedCourseTitles holds details about calls to the GetAssignedCourseTitles method.
		GetAssignedCourseTitles []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// S is the s argument value.
			S string
		}
		// GetCourse holds details about calls to the GetCourse method.
		GetCourse []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// UUID is the uUID argument value.
			UUID pgtype.UUID
		}
		// GetCourseMaterials holds details about calls to the GetCourseMaterials method.
		GetCourseMaterials []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// UUID is the uUID argument value.
			UUID uuid.UUID
		}
		// GetCoursesOverview holds details about calls to the GetCoursesOverview method.
		GetCoursesOverview []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
		}
	}
	lockAddCourse               sync.RWMutex
	lockDeleteCourse            sync.RWMutex
	lockEditCourse              sync.RWMutex
	lockGetAllCourses           sync.RWMutex
	lockGetAssignedCourseTitles sync.RWMutex
	lockGetCourse               sync.RWMutex
	lockGetCourseMaterials      sync.RWMutex
	lockGetCoursesOverview      sync.RWMutex
}

// AddCourse calls AddCourseFunc.
func (mock *CourseRepositoryMock) AddCourse(contextMoqParam context.Context, addCourseParams *domain.AddCourseParams) (*domain.Course, error) {
	if mock.AddCourseFunc == nil {
		panic("CourseRepositoryMock.AddCourseFunc: method is nil but CourseRepository.AddCourse was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		AddCourseParams *domain.AddCourseParams
	}{
		ContextMoqParam: contextMoqParam,
		AddCourseParams: addCourseParams,
	}
	mock.lockAddCourse.Lock()
	mock.calls.AddCourse = append(mock.calls.AddCourse, callInfo)
	mock.lockAddCourse.Unlock()
	return mock.AddCourseFunc(contextMoqParam, addCourseParams)
}

// AddCourseCalls gets all the calls that were made to AddCourse.
// Check the length with:
//
//	len(mockedCourseRepository.AddCourseCalls())
func (mock *CourseRepositoryMock) AddCourseCalls() []struct {
	ContextMoqParam context.Context
	AddCourseParams *domain.AddCourseParams
} {
	var calls []struct {
		ContextMoqParam context.Context
		AddCourseParams *domain.AddCourseParams
	}
	mock.lockAddCourse.RLock()
	calls = mock.calls.AddCourse
	mock.lockAddCourse.RUnlock()
	return calls
}

// DeleteCourse calls DeleteCourseFunc.
func (mock *CourseRepositoryMock) DeleteCourse(contextMoqParam context.Context, uUID uuid.UUID) error {
	if mock.DeleteCourseFunc == nil {
		panic("CourseRepositoryMock.DeleteCourseFunc: method is nil but CourseRepository.DeleteCourse was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		UUID            uuid.UUID
	}{
		ContextMoqParam: contextMoqParam,
		UUID:            uUID,
	}
	mock.lockDeleteCourse.Lock()
	mock.calls.DeleteCourse = append(mock.calls.DeleteCourse, callInfo)
	mock.lockDeleteCourse.Unlock()
	return mock.DeleteCourseFunc(contextMoqParam, uUID)
}

// DeleteCourseCalls gets all the calls that were made to DeleteCourse.
// Check the length with:
//
//	len(mockedCourseRepository.DeleteCourseCalls())
func (mock *CourseRepositoryMock) DeleteCourseCalls() []struct {
	ContextMoqParam context.Context
	UUID            uuid.UUID
} {
	var calls []struct {
		ContextMoqParam context.Context
		UUID            uuid.UUID
	}
	mock.lockDeleteCourse.RLock()
	calls = mock.calls.DeleteCourse
	mock.lockDeleteCourse.RUnlock()
	return calls
}

// EditCourse calls EditCourseFunc.
func (mock *CourseRepositoryMock) EditCourse(contextMoqParam context.Context, editCourseParams *domain.EditCourseParams) (*domain.Course, error) {
	if mock.EditCourseFunc == nil {
		panic("CourseRepositoryMock.EditCourseFunc: method is nil but CourseRepository.EditCourse was just called")
	}
	callInfo := struct {
		ContextMoqParam  context.Context
		EditCourseParams *domain.EditCourseParams
	}{
		ContextMoqParam:  contextMoqParam,
		EditCourseParams: editCourseParams,
	}
	mock.lockEditCourse.Lock()
	mock.calls.EditCourse = append(mock.calls.EditCourse, callInfo)
	mock.lockEditCourse.Unlock()
	return mock.EditCourseFunc(contextMoqParam, editCourseParams)
}

// EditCourseCalls gets all the calls that were made to EditCourse.
// Check the length with:
//
//	len(mockedCourseRepository.EditCourseCalls())
func (mock *CourseRepositoryMock) EditCourseCalls() []struct {
	ContextMoqParam  context.Context
	EditCourseParams *domain.EditCourseParams
} {
	var calls []struct {
		ContextMoqParam  context.Context
		EditCourseParams *domain.EditCourseParams
	}
	mock.lockEditCourse.RLock()
	calls = mock.calls.EditCourse
	mock.lockEditCourse.RUnlock()
	return calls
}

// GetAllCourses calls GetAllCoursesFunc.
func (mock *CourseRepositoryMock) GetAllCourses(contextMoqParam context.Context) ([]*domain.AllCourseLegacy, error) {
	if mock.GetAllCoursesFunc == nil {
		panic("CourseRepositoryMock.GetAllCoursesFunc: method is nil but CourseRepository.GetAllCourses was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
	}{
		ContextMoqParam: contextMoqParam,
	}
	mock.lockGetAllCourses.Lock()
	mock.calls.GetAllCourses = append(mock.calls.GetAllCourses, callInfo)
	mock.lockGetAllCourses.Unlock()
	return mock.GetAllCoursesFunc(contextMoqParam)
}

// GetAllCoursesCalls gets all the calls that were made to GetAllCourses.
// Check the length with:
//
//	len(mockedCourseRepository.GetAllCoursesCalls())
func (mock *CourseRepositoryMock) GetAllCoursesCalls() []struct {
	ContextMoqParam context.Context
} {
	var calls []struct {
		ContextMoqParam context.Context
	}
	mock.lockGetAllCourses.RLock()
	calls = mock.calls.GetAllCourses
	mock.lockGetAllCourses.RUnlock()
	return calls
}

// GetAssignedCourseTitles calls GetAssignedCourseTitlesFunc.
func (mock *CourseRepositoryMock) GetAssignedCourseTitles(contextMoqParam context.Context, s string) ([]domain.CourseOverview, error) {
	if mock.GetAssignedCourseTitlesFunc == nil {
		panic("CourseRepositoryMock.GetAssignedCourseTitlesFunc: method is nil but CourseRepository.GetAssignedCourseTitles was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		S               string
	}{
		ContextMoqParam: contextMoqParam,
		S:               s,
	}
	mock.lockGetAssignedCourseTitles.Lock()
	mock.calls.GetAssignedCourseTitles = append(mock.calls.GetAssignedCourseTitles, callInfo)
	mock.lockGetAssignedCourseTitles.Unlock()
	return mock.GetAssignedCourseTitlesFunc(contextMoqParam, s)
}

// GetAssignedCourseTitlesCalls gets all the calls that were made to GetAssignedCourseTitles.
// Check the length with:
//
//	len(mockedCourseRepository.GetAssignedCourseTitlesCalls())
func (mock *CourseRepositoryMock) GetAssignedCourseTitlesCalls() []struct {
	ContextMoqParam context.Context
	S               string
} {
	var calls []struct {
		ContextMoqParam context.Context
		S               string
	}
	mock.lockGetAssignedCourseTitles.RLock()
	calls = mock.calls.GetAssignedCourseTitles
	mock.lockGetAssignedCourseTitles.RUnlock()
	return calls
}

// GetCourse calls GetCourseFunc.
func (mock *CourseRepositoryMock) GetCourse(contextMoqParam context.Context, uUID pgtype.UUID) (*domain.Course, error) {
	if mock.GetCourseFunc == nil {
		panic("CourseRepositoryMock.GetCourseFunc: method is nil but CourseRepository.GetCourse was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		UUID            pgtype.UUID
	}{
		ContextMoqParam: contextMoqParam,
		UUID:            uUID,
	}
	mock.lockGetCourse.Lock()
	mock.calls.GetCourse = append(mock.calls.GetCourse, callInfo)
	mock.lockGetCourse.Unlock()
	return mock.GetCourseFunc(contextMoqParam, uUID)
}

// GetCourseCalls gets all the calls that were made to GetCourse.
// Check the length with:
//
//	len(mockedCourseRepository.GetCourseCalls())
func (mock *CourseRepositoryMock) GetCourseCalls() []struct {
	ContextMoqParam context.Context
	UUID            pgtype.UUID
} {
	var calls []struct {
		ContextMoqParam context.Context
		UUID            pgtype.UUID
	}
	mock.lockGetCourse.RLock()
	calls = mock.calls.GetCourse
	mock.lockGetCourse.RUnlock()
	return calls
}

// GetCourseMaterials calls GetCourseMaterialsFunc.
func (mock *CourseRepositoryMock) GetCourseMaterials(contextMoqParam context.Context, uUID uuid.UUID) ([]domain.CourseMaterial, error) {
	if mock.GetCourseMaterialsFunc == nil {
		panic("CourseRepositoryMock.GetCourseMaterialsFunc: method is nil but CourseRepository.GetCourseMaterials was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		UUID            uuid.UUID
	}{
		ContextMoqParam: contextMoqParam,
		UUID:            uUID,
	}
	mock.lockGetCourseMaterials.Lock()
	mock.calls.GetCourseMaterials = append(mock.calls.GetCourseMaterials, callInfo)
	mock.lockGetCourseMaterials.Unlock()
	return mock.GetCourseMaterialsFunc(contextMoqParam, uUID)
}

// GetCourseMaterialsCalls gets all the calls that were made to GetCourseMaterials.
// Check the length with:
//
//	len(mockedCourseRepository.GetCourseMaterialsCalls())
func (mock *CourseRepositoryMock) GetCourseMaterialsCalls() []struct {
	ContextMoqParam context.Context
	UUID            uuid.UUID
} {
	var calls []struct {
		ContextMoqParam context.Context
		UUID            uuid.UUID
	}
	mock.lockGetCourseMaterials.RLock()
	calls = mock.calls.GetCourseMaterials
	mock.lockGetCourseMaterials.RUnlock()
	return calls
}

// GetCoursesOverview calls GetCoursesOverviewFunc.
func (mock *CourseRepositoryMock) GetCoursesOverview(contextMoqParam context.Context) ([]domain.CourseOverview, error) {
	if mock.GetCoursesOverviewFunc == nil {
		panic("CourseRepositoryMock.GetCoursesOverviewFunc: method is nil but CourseRepository.GetCoursesOverview was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
	}{
		ContextMoqParam: contextMoqParam,
	}
	mock.lockGetCoursesOverview.Lock()
	mock.calls.GetCoursesOverview = append(mock.calls.GetCoursesOverview, callInfo)
	mock.lockGetCoursesOverview.Unlock()
	return mock.GetCoursesOverviewFunc(contextMoqParam)
}

// GetCoursesOverviewCalls gets all the calls that were made to GetCoursesOverview.
// Check the length with:
//
//	len(mockedCourseRepository.GetCoursesOverviewCalls())
func (mock *CourseRepositoryMock) GetCoursesOverviewCalls() []struct {
	ContextMoqParam context.Context
} {
	var calls []struct {
		ContextMoqParam context.Context
	}
	mock.lockGetCoursesOverview.RLock()
	calls = mock.calls.GetCoursesOverview
	mock.lockGetCoursesOverview.RUnlock()
	return calls
}
