// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/supanova-rp/supanova-server/internal/handlers"
	"github.com/supanova-rp/supanova-server/internal/services/email"
	"sync"
)

// Ensure, that EmailServiceMock does implement handlers.EmailService.
// If this is not the case, regenerate this file with moq.
var _ handlers.EmailService = &EmailServiceMock{}

// EmailServiceMock is a mock implementation of handlers.EmailService.
//
//	func TestSomethingThatUsesEmailService(t *testing.T) {
//
//		// make and configure a mocked handlers.EmailService
//		mockedEmailService := &EmailServiceMock{
//			GetTemplateNamesFunc: func() *email.TemplateNames {
//				panic("mock out the GetTemplateNames method")
//			},
//			SendFunc: func(ctx context.Context, params email.EmailParams, templateName string) error {
//				panic("mock out the Send method")
//			},
//		}
//
//		// use mockedEmailService in code that requires handlers.EmailService
//		// and then make assertions.
//
//	}
type EmailServiceMock struct {
	// GetTemplateNamesFunc mocks the GetTemplateNames method.
	GetTemplateNamesFunc func() *email.TemplateNames

	// SendFunc mocks the Send method.
	SendFunc func(ctx context.Context, params email.EmailParams, templateName string) error

	// calls tracks calls to the methods.
	calls struct {
		// GetTemplateNames holds details about calls to the GetTemplateNames method.
		GetTemplateNames []struct {
		}
		// Send holds details about calls to the Send method.
		Send []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Params is the params argument value.
			Params email.EmailParams
			// TemplateName is the templateName argument value.
			TemplateName string
		}
	}
	lockGetTemplateNames sync.RWMutex
	lockSend             sync.RWMutex
}

// GetTemplateNames calls GetTemplateNamesFunc.
func (mock *EmailServiceMock) GetTemplateNames() *email.TemplateNames {
	if mock.GetTemplateNamesFunc == nil {
		panic("EmailServiceMock.GetTemplateNamesFunc: method is nil but EmailService.GetTemplateNames was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetTemplateNames.Lock()
	mock.calls.GetTemplateNames = append(mock.calls.GetTemplateNames, callInfo)
	mock.lockGetTemplateNames.Unlock()
	return mock.GetTemplateNamesFunc()
}

// GetTemplateNamesCalls gets all the calls that were made to GetTemplateNames.
// Check the length with:
//
//	len(mockedEmailService.GetTemplateNamesCalls())
func (mock *EmailServiceMock) GetTemplateNamesCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetTemplateNames.RLock()
	calls = mock.calls.GetTemplateNames
	mock.lockGetTemplateNames.RUnlock()
	return calls
}

// Send calls SendFunc.
func (mock *EmailServiceMock) Send(ctx context.Context, params email.EmailParams, templateName string) error {
	if mock.SendFunc == nil {
		panic("EmailServiceMock.SendFunc: method is nil but EmailService.Send was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		Params       email.EmailParams
		TemplateName string
	}{
		Ctx:          ctx,
		Params:       params,
		TemplateName: templateName,
	}
	mock.lockSend.Lock()
	mock.calls.Send = append(mock.calls.Send, callInfo)
	mock.lockSend.Unlock()
	return mock.SendFunc(ctx, params, templateName)
}

// SendCalls gets all the calls that were made to Send.
// Check the length with:
//
//	len(mockedEmailService.SendCalls())
func (mock *EmailServiceMock) SendCalls() []struct {
	Ctx          context.Context
	Params       email.EmailParams
	TemplateName string
} {
	var calls []struct {
		Ctx          context.Context
		Params       email.EmailParams
		TemplateName string
	}
	mock.lockSend.RLock()
	calls = mock.calls.Send
	mock.lockSend.RUnlock()
	return calls
}
