// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/supanova-rp/supanova-server/internal/handlers"
	"github.com/supanova-rp/supanova-server/internal/services/email"
	"sync"
)

// Ensure, that EmailServiceMock does implement handlers.EmailService.
// If this is not the case, regenerate this file with moq.
var _ handlers.EmailService = &EmailServiceMock{}

// EmailServiceMock is a mock implementation of handlers.EmailService.
//
//	func TestSomethingThatUsesEmailService(t *testing.T) {
//
//		// make and configure a mocked handlers.EmailService
//		mockedEmailService := &EmailServiceMock{
//			SendCourseCompletionFunc: func(ctx context.Context, params *email.CourseCompletionParams) error {
//				panic("mock out the SendCourseCompletion method")
//			},
//		}
//
//		// use mockedEmailService in code that requires handlers.EmailService
//		// and then make assertions.
//
//	}
type EmailServiceMock struct {
	// SendCourseCompletionFunc mocks the SendCourseCompletion method.
	SendCourseCompletionFunc func(ctx context.Context, params *email.CourseCompletionParams) error

	// calls tracks calls to the methods.
	calls struct {
		// SendCourseCompletion holds details about calls to the SendCourseCompletion method.
		SendCourseCompletion []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Params is the params argument value.
			Params *email.CourseCompletionParams
		}
	}
	lockSendCourseCompletion sync.RWMutex
}

// SendCourseCompletion calls SendCourseCompletionFunc.
func (mock *EmailServiceMock) SendCourseCompletion(ctx context.Context, params *email.CourseCompletionParams) error {
	if mock.SendCourseCompletionFunc == nil {
		panic("EmailServiceMock.SendCourseCompletionFunc: method is nil but EmailService.SendCourseCompletion was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Params *email.CourseCompletionParams
	}{
		Ctx:    ctx,
		Params: params,
	}
	mock.lockSendCourseCompletion.Lock()
	mock.calls.SendCourseCompletion = append(mock.calls.SendCourseCompletion, callInfo)
	mock.lockSendCourseCompletion.Unlock()
	return mock.SendCourseCompletionFunc(ctx, params)
}

// SendCourseCompletionCalls gets all the calls that were made to SendCourseCompletion.
// Check the length with:
//
//	len(mockedEmailService.SendCourseCompletionCalls())
func (mock *EmailServiceMock) SendCourseCompletionCalls() []struct {
	Ctx    context.Context
	Params *email.CourseCompletionParams
} {
	var calls []struct {
		Ctx    context.Context
		Params *email.CourseCompletionParams
	}
	mock.lockSendCourseCompletion.RLock()
	calls = mock.calls.SendCourseCompletion
	mock.lockSendCourseCompletion.RUnlock()
	return calls
}
