// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/supanova-rp/supanova-server/internal/domain"
	"github.com/supanova-rp/supanova-server/internal/store/sqlc"
	"sync"
)

// Ensure, that EnrollmentRepositoryMock does implement domain.EnrollmentRepository.
// If this is not the case, regenerate this file with moq.
var _ domain.EnrollmentRepository = &EnrollmentRepositoryMock{}

// EnrollmentRepositoryMock is a mock implementation of domain.EnrollmentRepository.
//
//	func TestSomethingThatUsesEnrollmentRepository(t *testing.T) {
//
//		// make and configure a mocked domain.EnrollmentRepository
//		mockedEnrollmentRepository := &EnrollmentRepositoryMock{
//			IsEnrolledFunc: func(ctx context.Context, params sqlc.IsUserEnrolledInCourseParams) (bool, error) {
//				panic("mock out the IsEnrolled method")
//			},
//		}
//
//		// use mockedEnrollmentRepository in code that requires domain.EnrollmentRepository
//		// and then make assertions.
//
//	}
type EnrollmentRepositoryMock struct {
	// IsEnrolledFunc mocks the IsEnrolled method.
	IsEnrolledFunc func(ctx context.Context, params sqlc.IsUserEnrolledInCourseParams) (bool, error)

	// calls tracks calls to the methods.
	calls struct {
		// IsEnrolled holds details about calls to the IsEnrolled method.
		IsEnrolled []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Params is the params argument value.
			Params sqlc.IsUserEnrolledInCourseParams
		}
	}
	lockIsEnrolled sync.RWMutex
}

// IsEnrolled calls IsEnrolledFunc.
func (mock *EnrollmentRepositoryMock) IsEnrolled(ctx context.Context, params sqlc.IsUserEnrolledInCourseParams) (bool, error) {
	if mock.IsEnrolledFunc == nil {
		panic("EnrollmentRepositoryMock.IsEnrolledFunc: method is nil but EnrollmentRepository.IsEnrolled was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Params sqlc.IsUserEnrolledInCourseParams
	}{
		Ctx:    ctx,
		Params: params,
	}
	mock.lockIsEnrolled.Lock()
	mock.calls.IsEnrolled = append(mock.calls.IsEnrolled, callInfo)
	mock.lockIsEnrolled.Unlock()
	return mock.IsEnrolledFunc(ctx, params)
}

// IsEnrolledCalls gets all the calls that were made to IsEnrolled.
// Check the length with:
//
//	len(mockedEnrollmentRepository.IsEnrolledCalls())
func (mock *EnrollmentRepositoryMock) IsEnrolledCalls() []struct {
	Ctx    context.Context
	Params sqlc.IsUserEnrolledInCourseParams
} {
	var calls []struct {
		Ctx    context.Context
		Params sqlc.IsUserEnrolledInCourseParams
	}
	mock.lockIsEnrolled.RLock()
	calls = mock.calls.IsEnrolled
	mock.lockIsEnrolled.RUnlock()
	return calls
}
