// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/supanova-rp/supanova-server/internal/domain"
	"github.com/supanova-rp/supanova-server/internal/store/sqlc"
	"sync"
)

// Ensure, that EnrollmentRepositoryMock does implement domain.EnrollmentRepository.
// If this is not the case, regenerate this file with moq.
var _ domain.EnrollmentRepository = &EnrollmentRepositoryMock{}

// EnrollmentRepositoryMock is a mock implementation of domain.EnrollmentRepository.
//
//	func TestSomethingThatUsesEnrollmentRepository(t *testing.T) {
//
//		// make and configure a mocked domain.EnrollmentRepository
//		mockedEnrollmentRepository := &EnrollmentRepositoryMock{
//			DisenrollUserInCourseFunc: func(ctx context.Context, params sqlc.DisenrollUserInCourseParams) error {
//				panic("mock out the DisenrollUserInCourse method")
//			},
//			EnrollUserInCourseFunc: func(ctx context.Context, params sqlc.EnrollUserInCourseParams) error {
//				panic("mock out the EnrollUserInCourse method")
//			},
//			IsEnrolledFunc: func(ctx context.Context, params sqlc.IsUserEnrolledInCourseParams) (bool, error) {
//				panic("mock out the IsEnrolled method")
//			},
//		}
//
//		// use mockedEnrollmentRepository in code that requires domain.EnrollmentRepository
//		// and then make assertions.
//
//	}
type EnrollmentRepositoryMock struct {
	// DisenrollUserInCourseFunc mocks the DisenrollUserInCourse method.
	DisenrollUserInCourseFunc func(ctx context.Context, params sqlc.DisenrollUserInCourseParams) error

	// EnrollUserInCourseFunc mocks the EnrollUserInCourse method.
	EnrollUserInCourseFunc func(ctx context.Context, params sqlc.EnrollUserInCourseParams) error

	// IsEnrolledFunc mocks the IsEnrolled method.
	IsEnrolledFunc func(ctx context.Context, params sqlc.IsUserEnrolledInCourseParams) (bool, error)

	// calls tracks calls to the methods.
	calls struct {
		// DisenrollUserInCourse holds details about calls to the DisenrollUserInCourse method.
		DisenrollUserInCourse []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Params is the params argument value.
			Params sqlc.DisenrollUserInCourseParams
		}
		// EnrollUserInCourse holds details about calls to the EnrollUserInCourse method.
		EnrollUserInCourse []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Params is the params argument value.
			Params sqlc.EnrollUserInCourseParams
		}
		// IsEnrolled holds details about calls to the IsEnrolled method.
		IsEnrolled []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Params is the params argument value.
			Params sqlc.IsUserEnrolledInCourseParams
		}
	}
	lockDisenrollUserInCourse sync.RWMutex
	lockEnrollUserInCourse    sync.RWMutex
	lockIsEnrolled            sync.RWMutex
}

// DisenrollUserInCourse calls DisenrollUserInCourseFunc.
func (mock *EnrollmentRepositoryMock) DisenrollUserInCourse(ctx context.Context, params sqlc.DisenrollUserInCourseParams) error {
	if mock.DisenrollUserInCourseFunc == nil {
		panic("EnrollmentRepositoryMock.DisenrollUserInCourseFunc: method is nil but EnrollmentRepository.DisenrollUserInCourse was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Params sqlc.DisenrollUserInCourseParams
	}{
		Ctx:    ctx,
		Params: params,
	}
	mock.lockDisenrollUserInCourse.Lock()
	mock.calls.DisenrollUserInCourse = append(mock.calls.DisenrollUserInCourse, callInfo)
	mock.lockDisenrollUserInCourse.Unlock()
	return mock.DisenrollUserInCourseFunc(ctx, params)
}

// DisenrollUserInCourseCalls gets all the calls that were made to DisenrollUserInCourse.
// Check the length with:
//
//	len(mockedEnrollmentRepository.DisenrollUserInCourseCalls())
func (mock *EnrollmentRepositoryMock) DisenrollUserInCourseCalls() []struct {
	Ctx    context.Context
	Params sqlc.DisenrollUserInCourseParams
} {
	var calls []struct {
		Ctx    context.Context
		Params sqlc.DisenrollUserInCourseParams
	}
	mock.lockDisenrollUserInCourse.RLock()
	calls = mock.calls.DisenrollUserInCourse
	mock.lockDisenrollUserInCourse.RUnlock()
	return calls
}

// EnrollUserInCourse calls EnrollUserInCourseFunc.
func (mock *EnrollmentRepositoryMock) EnrollUserInCourse(ctx context.Context, params sqlc.EnrollUserInCourseParams) error {
	if mock.EnrollUserInCourseFunc == nil {
		panic("EnrollmentRepositoryMock.EnrollUserInCourseFunc: method is nil but EnrollmentRepository.EnrollUserInCourse was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Params sqlc.EnrollUserInCourseParams
	}{
		Ctx:    ctx,
		Params: params,
	}
	mock.lockEnrollUserInCourse.Lock()
	mock.calls.EnrollUserInCourse = append(mock.calls.EnrollUserInCourse, callInfo)
	mock.lockEnrollUserInCourse.Unlock()
	return mock.EnrollUserInCourseFunc(ctx, params)
}

// EnrollUserInCourseCalls gets all the calls that were made to EnrollUserInCourse.
// Check the length with:
//
//	len(mockedEnrollmentRepository.EnrollUserInCourseCalls())
func (mock *EnrollmentRepositoryMock) EnrollUserInCourseCalls() []struct {
	Ctx    context.Context
	Params sqlc.EnrollUserInCourseParams
} {
	var calls []struct {
		Ctx    context.Context
		Params sqlc.EnrollUserInCourseParams
	}
	mock.lockEnrollUserInCourse.RLock()
	calls = mock.calls.EnrollUserInCourse
	mock.lockEnrollUserInCourse.RUnlock()
	return calls
}

// IsEnrolled calls IsEnrolledFunc.
func (mock *EnrollmentRepositoryMock) IsEnrolled(ctx context.Context, params sqlc.IsUserEnrolledInCourseParams) (bool, error) {
	if mock.IsEnrolledFunc == nil {
		panic("EnrollmentRepositoryMock.IsEnrolledFunc: method is nil but EnrollmentRepository.IsEnrolled was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Params sqlc.IsUserEnrolledInCourseParams
	}{
		Ctx:    ctx,
		Params: params,
	}
	mock.lockIsEnrolled.Lock()
	mock.calls.IsEnrolled = append(mock.calls.IsEnrolled, callInfo)
	mock.lockIsEnrolled.Unlock()
	return mock.IsEnrolledFunc(ctx, params)
}

// IsEnrolledCalls gets all the calls that were made to IsEnrolled.
// Check the length with:
//
//	len(mockedEnrollmentRepository.IsEnrolledCalls())
func (mock *EnrollmentRepositoryMock) IsEnrolledCalls() []struct {
	Ctx    context.Context
	Params sqlc.IsUserEnrolledInCourseParams
} {
	var calls []struct {
		Ctx    context.Context
		Params sqlc.IsUserEnrolledInCourseParams
	}
	mock.lockIsEnrolled.RLock()
	calls = mock.calls.IsEnrolled
	mock.lockIsEnrolled.RUnlock()
	return calls
}
