// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/supanova-rp/supanova-server/internal/domain"
	"github.com/supanova-rp/supanova-server/internal/store/sqlc"
	"sync"
)

// Ensure, that EnrolmentRepositoryMock does implement domain.EnrolmentRepository.
// If this is not the case, regenerate this file with moq.
var _ domain.EnrolmentRepository = &EnrolmentRepositoryMock{}

// EnrolmentRepositoryMock is a mock implementation of domain.EnrolmentRepository.
//
//	func TestSomethingThatUsesEnrolmentRepository(t *testing.T) {
//
//		// make and configure a mocked domain.EnrolmentRepository
//		mockedEnrolmentRepository := &EnrolmentRepositoryMock{
//			DisenrolInCourseFunc: func(ctx context.Context, params sqlc.DisenrolInCourseParams) error {
//				panic("mock out the DisenrolInCourse method")
//			},
//			EnrolInCourseFunc: func(ctx context.Context, params sqlc.EnrolInCourseParams) error {
//				panic("mock out the EnrolInCourse method")
//			},
//			IsEnrolledFunc: func(ctx context.Context, params sqlc.IsUserEnrolledInCourseParams) (bool, error) {
//				panic("mock out the IsEnrolled method")
//			},
//		}
//
//		// use mockedEnrolmentRepository in code that requires domain.EnrolmentRepository
//		// and then make assertions.
//
//	}
type EnrolmentRepositoryMock struct {
	// DisenrolInCourseFunc mocks the DisenrolInCourse method.
	DisenrolInCourseFunc func(ctx context.Context, params sqlc.DisenrolInCourseParams) error

	// EnrolInCourseFunc mocks the EnrolInCourse method.
	EnrolInCourseFunc func(ctx context.Context, params sqlc.EnrolInCourseParams) error

	// IsEnrolledFunc mocks the IsEnrolled method.
	IsEnrolledFunc func(ctx context.Context, params sqlc.IsUserEnrolledInCourseParams) (bool, error)

	// calls tracks calls to the methods.
	calls struct {
		// DisenrolInCourse holds details about calls to the DisenrolInCourse method.
		DisenrolInCourse []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Params is the params argument value.
			Params sqlc.DisenrolInCourseParams
		}
		// EnrolInCourse holds details about calls to the EnrolInCourse method.
		EnrolInCourse []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Params is the params argument value.
			Params sqlc.EnrolInCourseParams
		}
		// IsEnrolled holds details about calls to the IsEnrolled method.
		IsEnrolled []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Params is the params argument value.
			Params sqlc.IsUserEnrolledInCourseParams
		}
	}
	lockDisenrolInCourse sync.RWMutex
	lockEnrolInCourse    sync.RWMutex
	lockIsEnrolled       sync.RWMutex
}

// DisenrolInCourse calls DisenrolInCourseFunc.
func (mock *EnrolmentRepositoryMock) DisenrolInCourse(ctx context.Context, params sqlc.DisenrolInCourseParams) error {
	if mock.DisenrolInCourseFunc == nil {
		panic("EnrolmentRepositoryMock.DisenrolInCourseFunc: method is nil but EnrolmentRepository.DisenrolInCourse was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Params sqlc.DisenrolInCourseParams
	}{
		Ctx:    ctx,
		Params: params,
	}
	mock.lockDisenrolInCourse.Lock()
	mock.calls.DisenrolInCourse = append(mock.calls.DisenrolInCourse, callInfo)
	mock.lockDisenrolInCourse.Unlock()
	return mock.DisenrolInCourseFunc(ctx, params)
}

// DisenrolInCourseCalls gets all the calls that were made to DisenrolInCourse.
// Check the length with:
//
//	len(mockedEnrolmentRepository.DisenrolInCourseCalls())
func (mock *EnrolmentRepositoryMock) DisenrolInCourseCalls() []struct {
	Ctx    context.Context
	Params sqlc.DisenrolInCourseParams
} {
	var calls []struct {
		Ctx    context.Context
		Params sqlc.DisenrolInCourseParams
	}
	mock.lockDisenrolInCourse.RLock()
	calls = mock.calls.DisenrolInCourse
	mock.lockDisenrolInCourse.RUnlock()
	return calls
}

// EnrolInCourse calls EnrolInCourseFunc.
func (mock *EnrolmentRepositoryMock) EnrolInCourse(ctx context.Context, params sqlc.EnrolInCourseParams) error {
	if mock.EnrolInCourseFunc == nil {
		panic("EnrolmentRepositoryMock.EnrolInCourseFunc: method is nil but EnrolmentRepository.EnrolInCourse was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Params sqlc.EnrolInCourseParams
	}{
		Ctx:    ctx,
		Params: params,
	}
	mock.lockEnrolInCourse.Lock()
	mock.calls.EnrolInCourse = append(mock.calls.EnrolInCourse, callInfo)
	mock.lockEnrolInCourse.Unlock()
	return mock.EnrolInCourseFunc(ctx, params)
}

// EnrolInCourseCalls gets all the calls that were made to EnrolInCourse.
// Check the length with:
//
//	len(mockedEnrolmentRepository.EnrolInCourseCalls())
func (mock *EnrolmentRepositoryMock) EnrolInCourseCalls() []struct {
	Ctx    context.Context
	Params sqlc.EnrolInCourseParams
} {
	var calls []struct {
		Ctx    context.Context
		Params sqlc.EnrolInCourseParams
	}
	mock.lockEnrolInCourse.RLock()
	calls = mock.calls.EnrolInCourse
	mock.lockEnrolInCourse.RUnlock()
	return calls
}

// IsEnrolled calls IsEnrolledFunc.
func (mock *EnrolmentRepositoryMock) IsEnrolled(ctx context.Context, params sqlc.IsUserEnrolledInCourseParams) (bool, error) {
	if mock.IsEnrolledFunc == nil {
		panic("EnrolmentRepositoryMock.IsEnrolledFunc: method is nil but EnrolmentRepository.IsEnrolled was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Params sqlc.IsUserEnrolledInCourseParams
	}{
		Ctx:    ctx,
		Params: params,
	}
	mock.lockIsEnrolled.Lock()
	mock.calls.IsEnrolled = append(mock.calls.IsEnrolled, callInfo)
	mock.lockIsEnrolled.Unlock()
	return mock.IsEnrolledFunc(ctx, params)
}

// IsEnrolledCalls gets all the calls that were made to IsEnrolled.
// Check the length with:
//
//	len(mockedEnrolmentRepository.IsEnrolledCalls())
func (mock *EnrolmentRepositoryMock) IsEnrolledCalls() []struct {
	Ctx    context.Context
	Params sqlc.IsUserEnrolledInCourseParams
} {
	var calls []struct {
		Ctx    context.Context
		Params sqlc.IsUserEnrolledInCourseParams
	}
	mock.lockIsEnrolled.RLock()
	calls = mock.calls.IsEnrolled
	mock.lockIsEnrolled.RUnlock()
	return calls
}
