// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/supanova-rp/supanova-server/internal/handlers"
	"sync"
)

// Ensure, that ObjectStorageMock does implement handlers.ObjectStorage.
// If this is not the case, regenerate this file with moq.
var _ handlers.ObjectStorage = &ObjectStorageMock{}

// ObjectStorageMock is a mock implementation of handlers.ObjectStorage.
//
//	func TestSomethingThatUsesObjectStorage(t *testing.T) {
//
//		// make and configure a mocked handlers.ObjectStorage
//		mockedObjectStorage := &ObjectStorageMock{
//			GenerateUploadURLFunc: func(ctx context.Context, key string, contentType *string) (string, error) {
//				panic("mock out the GenerateUploadURL method")
//			},
//			GetCDNURLFunc: func(ctx context.Context, key string) (string, error) {
//				panic("mock out the GetCDNURL method")
//			},
//		}
//
//		// use mockedObjectStorage in code that requires handlers.ObjectStorage
//		// and then make assertions.
//
//	}
type ObjectStorageMock struct {
	// GenerateUploadURLFunc mocks the GenerateUploadURL method.
	GenerateUploadURLFunc func(ctx context.Context, key string, contentType *string) (string, error)

	// GetCDNURLFunc mocks the GetCDNURL method.
	GetCDNURLFunc func(ctx context.Context, key string) (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// GenerateUploadURL holds details about calls to the GenerateUploadURL method.
		GenerateUploadURL []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
			// ContentType is the contentType argument value.
			ContentType *string
		}
		// GetCDNURL holds details about calls to the GetCDNURL method.
		GetCDNURL []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
		}
	}
	lockGenerateUploadURL sync.RWMutex
	lockGetCDNURL         sync.RWMutex
}

// GenerateUploadURL calls GenerateUploadURLFunc.
func (mock *ObjectStorageMock) GenerateUploadURL(ctx context.Context, key string, contentType *string) (string, error) {
	if mock.GenerateUploadURLFunc == nil {
		panic("ObjectStorageMock.GenerateUploadURLFunc: method is nil but ObjectStorage.GenerateUploadURL was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Key         string
		ContentType *string
	}{
		Ctx:         ctx,
		Key:         key,
		ContentType: contentType,
	}
	mock.lockGenerateUploadURL.Lock()
	mock.calls.GenerateUploadURL = append(mock.calls.GenerateUploadURL, callInfo)
	mock.lockGenerateUploadURL.Unlock()
	return mock.GenerateUploadURLFunc(ctx, key, contentType)
}

// GenerateUploadURLCalls gets all the calls that were made to GenerateUploadURL.
// Check the length with:
//
//	len(mockedObjectStorage.GenerateUploadURLCalls())
func (mock *ObjectStorageMock) GenerateUploadURLCalls() []struct {
	Ctx         context.Context
	Key         string
	ContentType *string
} {
	var calls []struct {
		Ctx         context.Context
		Key         string
		ContentType *string
	}
	mock.lockGenerateUploadURL.RLock()
	calls = mock.calls.GenerateUploadURL
	mock.lockGenerateUploadURL.RUnlock()
	return calls
}

// GetCDNURL calls GetCDNURLFunc.
func (mock *ObjectStorageMock) GetCDNURL(ctx context.Context, key string) (string, error) {
	if mock.GetCDNURLFunc == nil {
		panic("ObjectStorageMock.GetCDNURLFunc: method is nil but ObjectStorage.GetCDNURL was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Key string
	}{
		Ctx: ctx,
		Key: key,
	}
	mock.lockGetCDNURL.Lock()
	mock.calls.GetCDNURL = append(mock.calls.GetCDNURL, callInfo)
	mock.lockGetCDNURL.Unlock()
	return mock.GetCDNURLFunc(ctx, key)
}

// GetCDNURLCalls gets all the calls that were made to GetCDNURL.
// Check the length with:
//
//	len(mockedObjectStorage.GetCDNURLCalls())
func (mock *ObjectStorageMock) GetCDNURLCalls() []struct {
	Ctx context.Context
	Key string
} {
	var calls []struct {
		Ctx context.Context
		Key string
	}
	mock.lockGetCDNURL.RLock()
	calls = mock.calls.GetCDNURL
	mock.lockGetCDNURL.RUnlock()
	return calls
}
