// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/supanova-rp/supanova-server/internal/domain"
	"sync"
)

// Ensure, that ProgressRepositoryMock does implement domain.ProgressRepository.
// If this is not the case, regenerate this file with moq.
var _ domain.ProgressRepository = &ProgressRepositoryMock{}

// ProgressRepositoryMock is a mock implementation of domain.ProgressRepository.
//
//	func TestSomethingThatUsesProgressRepository(t *testing.T) {
//
//		// make and configure a mocked domain.ProgressRepository
//		mockedProgressRepository := &ProgressRepositoryMock{
//			GetAllProgressFunc: func(contextMoqParam context.Context) ([]*domain.FullProgress, error) {
//				panic("mock out the GetAllProgress method")
//			},
//			GetProgressFunc: func(contextMoqParam context.Context, getProgressParams domain.GetProgressParams) (*domain.Progress, error) {
//				panic("mock out the GetProgress method")
//			},
//			HasCompletedCourseFunc: func(contextMoqParam context.Context, hasCompletedCourseParams domain.HasCompletedCourseParams) (bool, error) {
//				panic("mock out the HasCompletedCourse method")
//			},
//			SetCourseCompletedFunc: func(contextMoqParam context.Context, setCourseCompletedParams domain.SetCourseCompletedParams) error {
//				panic("mock out the SetCourseCompleted method")
//			},
//			UpdateProgressFunc: func(contextMoqParam context.Context, updateProgressParams domain.UpdateProgressParams) error {
//				panic("mock out the UpdateProgress method")
//			},
//		}
//
//		// use mockedProgressRepository in code that requires domain.ProgressRepository
//		// and then make assertions.
//
//	}
type ProgressRepositoryMock struct {
	// GetAllProgressFunc mocks the GetAllProgress method.
	GetAllProgressFunc func(contextMoqParam context.Context) ([]*domain.FullProgress, error)

	// GetProgressFunc mocks the GetProgress method.
	GetProgressFunc func(contextMoqParam context.Context, getProgressParams domain.GetProgressParams) (*domain.Progress, error)

	// HasCompletedCourseFunc mocks the HasCompletedCourse method.
	HasCompletedCourseFunc func(contextMoqParam context.Context, hasCompletedCourseParams domain.HasCompletedCourseParams) (bool, error)

	// SetCourseCompletedFunc mocks the SetCourseCompleted method.
	SetCourseCompletedFunc func(contextMoqParam context.Context, setCourseCompletedParams domain.SetCourseCompletedParams) error

	// UpdateProgressFunc mocks the UpdateProgress method.
	UpdateProgressFunc func(contextMoqParam context.Context, updateProgressParams domain.UpdateProgressParams) error

	// calls tracks calls to the methods.
	calls struct {
		// GetAllProgress holds details about calls to the GetAllProgress method.
		GetAllProgress []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
		}
		// GetProgress holds details about calls to the GetProgress method.
		GetProgress []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// GetProgressParams is the getProgressParams argument value.
			GetProgressParams domain.GetProgressParams
		}
		// HasCompletedCourse holds details about calls to the HasCompletedCourse method.
		HasCompletedCourse []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// HasCompletedCourseParams is the hasCompletedCourseParams argument value.
			HasCompletedCourseParams domain.HasCompletedCourseParams
		}
		// SetCourseCompleted holds details about calls to the SetCourseCompleted method.
		SetCourseCompleted []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// SetCourseCompletedParams is the setCourseCompletedParams argument value.
			SetCourseCompletedParams domain.SetCourseCompletedParams
		}
		// UpdateProgress holds details about calls to the UpdateProgress method.
		UpdateProgress []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// UpdateProgressParams is the updateProgressParams argument value.
			UpdateProgressParams domain.UpdateProgressParams
		}
	}
	lockGetAllProgress     sync.RWMutex
	lockGetProgress        sync.RWMutex
	lockHasCompletedCourse sync.RWMutex
	lockSetCourseCompleted sync.RWMutex
	lockUpdateProgress     sync.RWMutex
}

// GetAllProgress calls GetAllProgressFunc.
func (mock *ProgressRepositoryMock) GetAllProgress(contextMoqParam context.Context) ([]*domain.FullProgress, error) {
	if mock.GetAllProgressFunc == nil {
		panic("ProgressRepositoryMock.GetAllProgressFunc: method is nil but ProgressRepository.GetAllProgress was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
	}{
		ContextMoqParam: contextMoqParam,
	}
	mock.lockGetAllProgress.Lock()
	mock.calls.GetAllProgress = append(mock.calls.GetAllProgress, callInfo)
	mock.lockGetAllProgress.Unlock()
	return mock.GetAllProgressFunc(contextMoqParam)
}

// GetAllProgressCalls gets all the calls that were made to GetAllProgress.
// Check the length with:
//
//	len(mockedProgressRepository.GetAllProgressCalls())
func (mock *ProgressRepositoryMock) GetAllProgressCalls() []struct {
	ContextMoqParam context.Context
} {
	var calls []struct {
		ContextMoqParam context.Context
	}
	mock.lockGetAllProgress.RLock()
	calls = mock.calls.GetAllProgress
	mock.lockGetAllProgress.RUnlock()
	return calls
}

// GetProgress calls GetProgressFunc.
func (mock *ProgressRepositoryMock) GetProgress(contextMoqParam context.Context, getProgressParams domain.GetProgressParams) (*domain.Progress, error) {
	if mock.GetProgressFunc == nil {
		panic("ProgressRepositoryMock.GetProgressFunc: method is nil but ProgressRepository.GetProgress was just called")
	}
	callInfo := struct {
		ContextMoqParam   context.Context
		GetProgressParams domain.GetProgressParams
	}{
		ContextMoqParam:   contextMoqParam,
		GetProgressParams: getProgressParams,
	}
	mock.lockGetProgress.Lock()
	mock.calls.GetProgress = append(mock.calls.GetProgress, callInfo)
	mock.lockGetProgress.Unlock()
	return mock.GetProgressFunc(contextMoqParam, getProgressParams)
}

// GetProgressCalls gets all the calls that were made to GetProgress.
// Check the length with:
//
//	len(mockedProgressRepository.GetProgressCalls())
func (mock *ProgressRepositoryMock) GetProgressCalls() []struct {
	ContextMoqParam   context.Context
	GetProgressParams domain.GetProgressParams
} {
	var calls []struct {
		ContextMoqParam   context.Context
		GetProgressParams domain.GetProgressParams
	}
	mock.lockGetProgress.RLock()
	calls = mock.calls.GetProgress
	mock.lockGetProgress.RUnlock()
	return calls
}

// HasCompletedCourse calls HasCompletedCourseFunc.
func (mock *ProgressRepositoryMock) HasCompletedCourse(contextMoqParam context.Context, hasCompletedCourseParams domain.HasCompletedCourseParams) (bool, error) {
	if mock.HasCompletedCourseFunc == nil {
		panic("ProgressRepositoryMock.HasCompletedCourseFunc: method is nil but ProgressRepository.HasCompletedCourse was just called")
	}
	callInfo := struct {
		ContextMoqParam          context.Context
		HasCompletedCourseParams domain.HasCompletedCourseParams
	}{
		ContextMoqParam:          contextMoqParam,
		HasCompletedCourseParams: hasCompletedCourseParams,
	}
	mock.lockHasCompletedCourse.Lock()
	mock.calls.HasCompletedCourse = append(mock.calls.HasCompletedCourse, callInfo)
	mock.lockHasCompletedCourse.Unlock()
	return mock.HasCompletedCourseFunc(contextMoqParam, hasCompletedCourseParams)
}

// HasCompletedCourseCalls gets all the calls that were made to HasCompletedCourse.
// Check the length with:
//
//	len(mockedProgressRepository.HasCompletedCourseCalls())
func (mock *ProgressRepositoryMock) HasCompletedCourseCalls() []struct {
	ContextMoqParam          context.Context
	HasCompletedCourseParams domain.HasCompletedCourseParams
} {
	var calls []struct {
		ContextMoqParam          context.Context
		HasCompletedCourseParams domain.HasCompletedCourseParams
	}
	mock.lockHasCompletedCourse.RLock()
	calls = mock.calls.HasCompletedCourse
	mock.lockHasCompletedCourse.RUnlock()
	return calls
}

// SetCourseCompleted calls SetCourseCompletedFunc.
func (mock *ProgressRepositoryMock) SetCourseCompleted(contextMoqParam context.Context, setCourseCompletedParams domain.SetCourseCompletedParams) error {
	if mock.SetCourseCompletedFunc == nil {
		panic("ProgressRepositoryMock.SetCourseCompletedFunc: method is nil but ProgressRepository.SetCourseCompleted was just called")
	}
	callInfo := struct {
		ContextMoqParam          context.Context
		SetCourseCompletedParams domain.SetCourseCompletedParams
	}{
		ContextMoqParam:          contextMoqParam,
		SetCourseCompletedParams: setCourseCompletedParams,
	}
	mock.lockSetCourseCompleted.Lock()
	mock.calls.SetCourseCompleted = append(mock.calls.SetCourseCompleted, callInfo)
	mock.lockSetCourseCompleted.Unlock()
	return mock.SetCourseCompletedFunc(contextMoqParam, setCourseCompletedParams)
}

// SetCourseCompletedCalls gets all the calls that were made to SetCourseCompleted.
// Check the length with:
//
//	len(mockedProgressRepository.SetCourseCompletedCalls())
func (mock *ProgressRepositoryMock) SetCourseCompletedCalls() []struct {
	ContextMoqParam          context.Context
	SetCourseCompletedParams domain.SetCourseCompletedParams
} {
	var calls []struct {
		ContextMoqParam          context.Context
		SetCourseCompletedParams domain.SetCourseCompletedParams
	}
	mock.lockSetCourseCompleted.RLock()
	calls = mock.calls.SetCourseCompleted
	mock.lockSetCourseCompleted.RUnlock()
	return calls
}

// UpdateProgress calls UpdateProgressFunc.
func (mock *ProgressRepositoryMock) UpdateProgress(contextMoqParam context.Context, updateProgressParams domain.UpdateProgressParams) error {
	if mock.UpdateProgressFunc == nil {
		panic("ProgressRepositoryMock.UpdateProgressFunc: method is nil but ProgressRepository.UpdateProgress was just called")
	}
	callInfo := struct {
		ContextMoqParam      context.Context
		UpdateProgressParams domain.UpdateProgressParams
	}{
		ContextMoqParam:      contextMoqParam,
		UpdateProgressParams: updateProgressParams,
	}
	mock.lockUpdateProgress.Lock()
	mock.calls.UpdateProgress = append(mock.calls.UpdateProgress, callInfo)
	mock.lockUpdateProgress.Unlock()
	return mock.UpdateProgressFunc(contextMoqParam, updateProgressParams)
}

// UpdateProgressCalls gets all the calls that were made to UpdateProgress.
// Check the length with:
//
//	len(mockedProgressRepository.UpdateProgressCalls())
func (mock *ProgressRepositoryMock) UpdateProgressCalls() []struct {
	ContextMoqParam      context.Context
	UpdateProgressParams domain.UpdateProgressParams
} {
	var calls []struct {
		ContextMoqParam      context.Context
		UpdateProgressParams domain.UpdateProgressParams
	}
	mock.lockUpdateProgress.RLock()
	calls = mock.calls.UpdateProgress
	mock.lockUpdateProgress.RUnlock()
	return calls
}
