// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/supanova-rp/supanova-server/internal/domain"
	"github.com/supanova-rp/supanova-server/internal/store/sqlc"
	"sync"
)

// Ensure, that ProgressRepositoryMock does implement domain.ProgressRepository.
// If this is not the case, regenerate this file with moq.
var _ domain.ProgressRepository = &ProgressRepositoryMock{}

// ProgressRepositoryMock is a mock implementation of domain.ProgressRepository.
//
//	func TestSomethingThatUsesProgressRepository(t *testing.T) {
//
//		// make and configure a mocked domain.ProgressRepository
//		mockedProgressRepository := &ProgressRepositoryMock{
//			GetProgressFunc: func(contextMoqParam context.Context, getProgressParams sqlc.GetProgressParams) (*domain.Progress, error) {
//				panic("mock out the GetProgress method")
//			},
//			UpdateProgressFunc: func(contextMoqParam context.Context, updateProgressParams sqlc.UpdateProgressParams) error {
//				panic("mock out the UpdateProgress method")
//			},
//		}
//
//		// use mockedProgressRepository in code that requires domain.ProgressRepository
//		// and then make assertions.
//
//	}
type ProgressRepositoryMock struct {
	// GetProgressFunc mocks the GetProgress method.
	GetProgressFunc func(contextMoqParam context.Context, getProgressParams sqlc.GetProgressParams) (*domain.Progress, error)

	// UpdateProgressFunc mocks the UpdateProgress method.
	UpdateProgressFunc func(contextMoqParam context.Context, updateProgressParams sqlc.UpdateProgressParams) error

	// calls tracks calls to the methods.
	calls struct {
		// GetProgress holds details about calls to the GetProgress method.
		GetProgress []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// GetProgressParams is the getProgressParams argument value.
			GetProgressParams sqlc.GetProgressParams
		}
		// UpdateProgress holds details about calls to the UpdateProgress method.
		UpdateProgress []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// UpdateProgressParams is the updateProgressParams argument value.
			UpdateProgressParams sqlc.UpdateProgressParams
		}
	}
	lockGetProgress    sync.RWMutex
	lockUpdateProgress sync.RWMutex
}

// GetProgress calls GetProgressFunc.
func (mock *ProgressRepositoryMock) GetProgress(contextMoqParam context.Context, getProgressParams sqlc.GetProgressParams) (*domain.Progress, error) {
	if mock.GetProgressFunc == nil {
		panic("ProgressRepositoryMock.GetProgressFunc: method is nil but ProgressRepository.GetProgress was just called")
	}
	callInfo := struct {
		ContextMoqParam   context.Context
		GetProgressParams sqlc.GetProgressParams
	}{
		ContextMoqParam:   contextMoqParam,
		GetProgressParams: getProgressParams,
	}
	mock.lockGetProgress.Lock()
	mock.calls.GetProgress = append(mock.calls.GetProgress, callInfo)
	mock.lockGetProgress.Unlock()
	return mock.GetProgressFunc(contextMoqParam, getProgressParams)
}

// GetProgressCalls gets all the calls that were made to GetProgress.
// Check the length with:
//
//	len(mockedProgressRepository.GetProgressCalls())
func (mock *ProgressRepositoryMock) GetProgressCalls() []struct {
	ContextMoqParam   context.Context
	GetProgressParams sqlc.GetProgressParams
} {
	var calls []struct {
		ContextMoqParam   context.Context
		GetProgressParams sqlc.GetProgressParams
	}
	mock.lockGetProgress.RLock()
	calls = mock.calls.GetProgress
	mock.lockGetProgress.RUnlock()
	return calls
}

// UpdateProgress calls UpdateProgressFunc.
func (mock *ProgressRepositoryMock) UpdateProgress(contextMoqParam context.Context, updateProgressParams sqlc.UpdateProgressParams) error {
	if mock.UpdateProgressFunc == nil {
		panic("ProgressRepositoryMock.UpdateProgressFunc: method is nil but ProgressRepository.UpdateProgress was just called")
	}
	callInfo := struct {
		ContextMoqParam      context.Context
		UpdateProgressParams sqlc.UpdateProgressParams
	}{
		ContextMoqParam:      contextMoqParam,
		UpdateProgressParams: updateProgressParams,
	}
	mock.lockUpdateProgress.Lock()
	mock.calls.UpdateProgress = append(mock.calls.UpdateProgress, callInfo)
	mock.lockUpdateProgress.Unlock()
	return mock.UpdateProgressFunc(contextMoqParam, updateProgressParams)
}

// UpdateProgressCalls gets all the calls that were made to UpdateProgress.
// Check the length with:
//
//	len(mockedProgressRepository.UpdateProgressCalls())
func (mock *ProgressRepositoryMock) UpdateProgressCalls() []struct {
	ContextMoqParam      context.Context
	UpdateProgressParams sqlc.UpdateProgressParams
} {
	var calls []struct {
		ContextMoqParam      context.Context
		UpdateProgressParams sqlc.UpdateProgressParams
	}
	mock.lockUpdateProgress.RLock()
	calls = mock.calls.UpdateProgress
	mock.lockUpdateProgress.RUnlock()
	return calls
}
