// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/google/uuid"
	"github.com/supanova-rp/supanova-server/internal/domain"
	"sync"
)

// Ensure, that QuizRepositoryMock does implement domain.QuizRepository.
// If this is not the case, regenerate this file with moq.
var _ domain.QuizRepository = &QuizRepositoryMock{}

// QuizRepositoryMock is a mock implementation of domain.QuizRepository.
//
//	func TestSomethingThatUsesQuizRepository(t *testing.T) {
//
//		// make and configure a mocked domain.QuizRepository
//		mockedQuizRepository := &QuizRepositoryMock{
//			GetAllQuizSectionsFunc: func(contextMoqParam context.Context) ([]*domain.QuizSection, error) {
//				panic("mock out the GetAllQuizSections method")
//			},
//			GetQuizAttemptsByUserIDFunc: func(contextMoqParam context.Context, s string) ([]*domain.QuizAttempts, error) {
//				panic("mock out the GetQuizAttemptsByUserID method")
//			},
//			GetQuizStateFunc: func(ctx context.Context, userID string, quizID uuid.UUID) (*domain.QuizState, error) {
//				panic("mock out the GetQuizState method")
//			},
//			ResetQuizProgressFunc: func(ctx context.Context, userID string, quizID uuid.UUID) error {
//				panic("mock out the ResetQuizProgress method")
//			},
//			SaveQuizAttemptFunc: func(contextMoqParam context.Context, saveQuizAttemptParams domain.SaveQuizAttemptParams) error {
//				panic("mock out the SaveQuizAttempt method")
//			},
//			SetQuizStateFunc: func(contextMoqParam context.Context, setQuizStateParams domain.SetQuizStateParams) error {
//				panic("mock out the SetQuizState method")
//			},
//			UpsertQuizStateFunc: func(contextMoqParam context.Context, upsertQuizStateParams domain.UpsertQuizStateParams) error {
//				panic("mock out the UpsertQuizState method")
//			},
//		}
//
//		// use mockedQuizRepository in code that requires domain.QuizRepository
//		// and then make assertions.
//
//	}
type QuizRepositoryMock struct {
	// GetAllQuizSectionsFunc mocks the GetAllQuizSections method.
	GetAllQuizSectionsFunc func(contextMoqParam context.Context) ([]*domain.QuizSection, error)

	// GetQuizAttemptsByUserIDFunc mocks the GetQuizAttemptsByUserID method.
	GetQuizAttemptsByUserIDFunc func(contextMoqParam context.Context, s string) ([]*domain.QuizAttempts, error)

	// GetQuizStateFunc mocks the GetQuizState method.
	GetQuizStateFunc func(ctx context.Context, userID string, quizID uuid.UUID) (*domain.QuizState, error)

	// ResetQuizProgressFunc mocks the ResetQuizProgress method.
	ResetQuizProgressFunc func(ctx context.Context, userID string, quizID uuid.UUID) error

	// SaveQuizAttemptFunc mocks the SaveQuizAttempt method.
	SaveQuizAttemptFunc func(contextMoqParam context.Context, saveQuizAttemptParams domain.SaveQuizAttemptParams) error

	// SetQuizStateFunc mocks the SetQuizState method.
	SetQuizStateFunc func(contextMoqParam context.Context, setQuizStateParams domain.SetQuizStateParams) error

	// UpsertQuizStateFunc mocks the UpsertQuizState method.
	UpsertQuizStateFunc func(contextMoqParam context.Context, upsertQuizStateParams domain.UpsertQuizStateParams) error

	// calls tracks calls to the methods.
	calls struct {
		// GetAllQuizSections holds details about calls to the GetAllQuizSections method.
		GetAllQuizSections []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
		}
		// GetQuizAttemptsByUserID holds details about calls to the GetQuizAttemptsByUserID method.
		GetQuizAttemptsByUserID []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// S is the s argument value.
			S string
		}
		// GetQuizState holds details about calls to the GetQuizState method.
		GetQuizState []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID string
			// QuizID is the quizID argument value.
			QuizID uuid.UUID
		}
		// ResetQuizProgress holds details about calls to the ResetQuizProgress method.
		ResetQuizProgress []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID string
			// QuizID is the quizID argument value.
			QuizID uuid.UUID
		}
		// SaveQuizAttempt holds details about calls to the SaveQuizAttempt method.
		SaveQuizAttempt []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// SaveQuizAttemptParams is the saveQuizAttemptParams argument value.
			SaveQuizAttemptParams domain.SaveQuizAttemptParams
		}
		// SetQuizState holds details about calls to the SetQuizState method.
		SetQuizState []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// SetQuizStateParams is the setQuizStateParams argument value.
			SetQuizStateParams domain.SetQuizStateParams
		}
		// UpsertQuizState holds details about calls to the UpsertQuizState method.
		UpsertQuizState []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// UpsertQuizStateParams is the upsertQuizStateParams argument value.
			UpsertQuizStateParams domain.UpsertQuizStateParams
		}
	}
	lockGetAllQuizSections      sync.RWMutex
	lockGetQuizAttemptsByUserID sync.RWMutex
	lockGetQuizState            sync.RWMutex
	lockResetQuizProgress       sync.RWMutex
	lockSaveQuizAttempt         sync.RWMutex
	lockSetQuizState            sync.RWMutex
	lockUpsertQuizState         sync.RWMutex
}

// GetAllQuizSections calls GetAllQuizSectionsFunc.
func (mock *QuizRepositoryMock) GetAllQuizSections(contextMoqParam context.Context) ([]*domain.QuizSection, error) {
	if mock.GetAllQuizSectionsFunc == nil {
		panic("QuizRepositoryMock.GetAllQuizSectionsFunc: method is nil but QuizRepository.GetAllQuizSections was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
	}{
		ContextMoqParam: contextMoqParam,
	}
	mock.lockGetAllQuizSections.Lock()
	mock.calls.GetAllQuizSections = append(mock.calls.GetAllQuizSections, callInfo)
	mock.lockGetAllQuizSections.Unlock()
	return mock.GetAllQuizSectionsFunc(contextMoqParam)
}

// GetAllQuizSectionsCalls gets all the calls that were made to GetAllQuizSections.
// Check the length with:
//
//	len(mockedQuizRepository.GetAllQuizSectionsCalls())
func (mock *QuizRepositoryMock) GetAllQuizSectionsCalls() []struct {
	ContextMoqParam context.Context
} {
	var calls []struct {
		ContextMoqParam context.Context
	}
	mock.lockGetAllQuizSections.RLock()
	calls = mock.calls.GetAllQuizSections
	mock.lockGetAllQuizSections.RUnlock()
	return calls
}

// GetQuizAttemptsByUserID calls GetQuizAttemptsByUserIDFunc.
func (mock *QuizRepositoryMock) GetQuizAttemptsByUserID(contextMoqParam context.Context, s string) ([]*domain.QuizAttempts, error) {
	if mock.GetQuizAttemptsByUserIDFunc == nil {
		panic("QuizRepositoryMock.GetQuizAttemptsByUserIDFunc: method is nil but QuizRepository.GetQuizAttemptsByUserID was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		S               string
	}{
		ContextMoqParam: contextMoqParam,
		S:               s,
	}
	mock.lockGetQuizAttemptsByUserID.Lock()
	mock.calls.GetQuizAttemptsByUserID = append(mock.calls.GetQuizAttemptsByUserID, callInfo)
	mock.lockGetQuizAttemptsByUserID.Unlock()
	return mock.GetQuizAttemptsByUserIDFunc(contextMoqParam, s)
}

// GetQuizAttemptsByUserIDCalls gets all the calls that were made to GetQuizAttemptsByUserID.
// Check the length with:
//
//	len(mockedQuizRepository.GetQuizAttemptsByUserIDCalls())
func (mock *QuizRepositoryMock) GetQuizAttemptsByUserIDCalls() []struct {
	ContextMoqParam context.Context
	S               string
} {
	var calls []struct {
		ContextMoqParam context.Context
		S               string
	}
	mock.lockGetQuizAttemptsByUserID.RLock()
	calls = mock.calls.GetQuizAttemptsByUserID
	mock.lockGetQuizAttemptsByUserID.RUnlock()
	return calls
}

// GetQuizState calls GetQuizStateFunc.
func (mock *QuizRepositoryMock) GetQuizState(ctx context.Context, userID string, quizID uuid.UUID) (*domain.QuizState, error) {
	if mock.GetQuizStateFunc == nil {
		panic("QuizRepositoryMock.GetQuizStateFunc: method is nil but QuizRepository.GetQuizState was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID string
		QuizID uuid.UUID
	}{
		Ctx:    ctx,
		UserID: userID,
		QuizID: quizID,
	}
	mock.lockGetQuizState.Lock()
	mock.calls.GetQuizState = append(mock.calls.GetQuizState, callInfo)
	mock.lockGetQuizState.Unlock()
	return mock.GetQuizStateFunc(ctx, userID, quizID)
}

// GetQuizStateCalls gets all the calls that were made to GetQuizState.
// Check the length with:
//
//	len(mockedQuizRepository.GetQuizStateCalls())
func (mock *QuizRepositoryMock) GetQuizStateCalls() []struct {
	Ctx    context.Context
	UserID string
	QuizID uuid.UUID
} {
	var calls []struct {
		Ctx    context.Context
		UserID string
		QuizID uuid.UUID
	}
	mock.lockGetQuizState.RLock()
	calls = mock.calls.GetQuizState
	mock.lockGetQuizState.RUnlock()
	return calls
}

// ResetQuizProgress calls ResetQuizProgressFunc.
func (mock *QuizRepositoryMock) ResetQuizProgress(ctx context.Context, userID string, quizID uuid.UUID) error {
	if mock.ResetQuizProgressFunc == nil {
		panic("QuizRepositoryMock.ResetQuizProgressFunc: method is nil but QuizRepository.ResetQuizProgress was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID string
		QuizID uuid.UUID
	}{
		Ctx:    ctx,
		UserID: userID,
		QuizID: quizID,
	}
	mock.lockResetQuizProgress.Lock()
	mock.calls.ResetQuizProgress = append(mock.calls.ResetQuizProgress, callInfo)
	mock.lockResetQuizProgress.Unlock()
	return mock.ResetQuizProgressFunc(ctx, userID, quizID)
}

// ResetQuizProgressCalls gets all the calls that were made to ResetQuizProgress.
// Check the length with:
//
//	len(mockedQuizRepository.ResetQuizProgressCalls())
func (mock *QuizRepositoryMock) ResetQuizProgressCalls() []struct {
	Ctx    context.Context
	UserID string
	QuizID uuid.UUID
} {
	var calls []struct {
		Ctx    context.Context
		UserID string
		QuizID uuid.UUID
	}
	mock.lockResetQuizProgress.RLock()
	calls = mock.calls.ResetQuizProgress
	mock.lockResetQuizProgress.RUnlock()
	return calls
}

// SaveQuizAttempt calls SaveQuizAttemptFunc.
func (mock *QuizRepositoryMock) SaveQuizAttempt(contextMoqParam context.Context, saveQuizAttemptParams domain.SaveQuizAttemptParams) error {
	if mock.SaveQuizAttemptFunc == nil {
		panic("QuizRepositoryMock.SaveQuizAttemptFunc: method is nil but QuizRepository.SaveQuizAttempt was just called")
	}
	callInfo := struct {
		ContextMoqParam       context.Context
		SaveQuizAttemptParams domain.SaveQuizAttemptParams
	}{
		ContextMoqParam:       contextMoqParam,
		SaveQuizAttemptParams: saveQuizAttemptParams,
	}
	mock.lockSaveQuizAttempt.Lock()
	mock.calls.SaveQuizAttempt = append(mock.calls.SaveQuizAttempt, callInfo)
	mock.lockSaveQuizAttempt.Unlock()
	return mock.SaveQuizAttemptFunc(contextMoqParam, saveQuizAttemptParams)
}

// SaveQuizAttemptCalls gets all the calls that were made to SaveQuizAttempt.
// Check the length with:
//
//	len(mockedQuizRepository.SaveQuizAttemptCalls())
func (mock *QuizRepositoryMock) SaveQuizAttemptCalls() []struct {
	ContextMoqParam       context.Context
	SaveQuizAttemptParams domain.SaveQuizAttemptParams
} {
	var calls []struct {
		ContextMoqParam       context.Context
		SaveQuizAttemptParams domain.SaveQuizAttemptParams
	}
	mock.lockSaveQuizAttempt.RLock()
	calls = mock.calls.SaveQuizAttempt
	mock.lockSaveQuizAttempt.RUnlock()
	return calls
}

// SetQuizState calls SetQuizStateFunc.
func (mock *QuizRepositoryMock) SetQuizState(contextMoqParam context.Context, setQuizStateParams domain.SetQuizStateParams) error {
	if mock.SetQuizStateFunc == nil {
		panic("QuizRepositoryMock.SetQuizStateFunc: method is nil but QuizRepository.SetQuizState was just called")
	}
	callInfo := struct {
		ContextMoqParam    context.Context
		SetQuizStateParams domain.SetQuizStateParams
	}{
		ContextMoqParam:    contextMoqParam,
		SetQuizStateParams: setQuizStateParams,
	}
	mock.lockSetQuizState.Lock()
	mock.calls.SetQuizState = append(mock.calls.SetQuizState, callInfo)
	mock.lockSetQuizState.Unlock()
	return mock.SetQuizStateFunc(contextMoqParam, setQuizStateParams)
}

// SetQuizStateCalls gets all the calls that were made to SetQuizState.
// Check the length with:
//
//	len(mockedQuizRepository.SetQuizStateCalls())
func (mock *QuizRepositoryMock) SetQuizStateCalls() []struct {
	ContextMoqParam    context.Context
	SetQuizStateParams domain.SetQuizStateParams
} {
	var calls []struct {
		ContextMoqParam    context.Context
		SetQuizStateParams domain.SetQuizStateParams
	}
	mock.lockSetQuizState.RLock()
	calls = mock.calls.SetQuizState
	mock.lockSetQuizState.RUnlock()
	return calls
}

// UpsertQuizState calls UpsertQuizStateFunc.
func (mock *QuizRepositoryMock) UpsertQuizState(contextMoqParam context.Context, upsertQuizStateParams domain.UpsertQuizStateParams) error {
	if mock.UpsertQuizStateFunc == nil {
		panic("QuizRepositoryMock.UpsertQuizStateFunc: method is nil but QuizRepository.UpsertQuizState was just called")
	}
	callInfo := struct {
		ContextMoqParam       context.Context
		UpsertQuizStateParams domain.UpsertQuizStateParams
	}{
		ContextMoqParam:       contextMoqParam,
		UpsertQuizStateParams: upsertQuizStateParams,
	}
	mock.lockUpsertQuizState.Lock()
	mock.calls.UpsertQuizState = append(mock.calls.UpsertQuizState, callInfo)
	mock.lockUpsertQuizState.Unlock()
	return mock.UpsertQuizStateFunc(contextMoqParam, upsertQuizStateParams)
}

// UpsertQuizStateCalls gets all the calls that were made to UpsertQuizState.
// Check the length with:
//
//	len(mockedQuizRepository.UpsertQuizStateCalls())
func (mock *QuizRepositoryMock) UpsertQuizStateCalls() []struct {
	ContextMoqParam       context.Context
	UpsertQuizStateParams domain.UpsertQuizStateParams
} {
	var calls []struct {
		ContextMoqParam       context.Context
		UpsertQuizStateParams domain.UpsertQuizStateParams
	}
	mock.lockUpsertQuizState.RLock()
	calls = mock.calls.UpsertQuizState
	mock.lockUpsertQuizState.RUnlock()
	return calls
}
