// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/supanova-rp/supanova-server/internal/domain"
	"sync"
)

// Ensure, that UserRepositoryMock does implement domain.UserRepository.
// If this is not the case, regenerate this file with moq.
var _ domain.UserRepository = &UserRepositoryMock{}

// UserRepositoryMock is a mock implementation of domain.UserRepository.
//
//	func TestSomethingThatUsesUserRepository(t *testing.T) {
//
//		// make and configure a mocked domain.UserRepository
//		mockedUserRepository := &UserRepositoryMock{
//			GetUserFunc: func(contextMoqParam context.Context, s string) (*domain.User, error) {
//				panic("mock out the GetUser method")
//			},
//			GetUsersAndAssignedCoursesFunc: func(contextMoqParam context.Context) ([]domain.UserWithAssignedCourses, error) {
//				panic("mock out the GetUsersAndAssignedCourses method")
//			},
//		}
//
//		// use mockedUserRepository in code that requires domain.UserRepository
//		// and then make assertions.
//
//	}
type UserRepositoryMock struct {
	// GetUserFunc mocks the GetUser method.
	GetUserFunc func(contextMoqParam context.Context, s string) (*domain.User, error)

	// GetUsersAndAssignedCoursesFunc mocks the GetUsersAndAssignedCourses method.
	GetUsersAndAssignedCoursesFunc func(contextMoqParam context.Context) ([]domain.UserWithAssignedCourses, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetUser holds details about calls to the GetUser method.
		GetUser []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// S is the s argument value.
			S string
		}
		// GetUsersAndAssignedCourses holds details about calls to the GetUsersAndAssignedCourses method.
		GetUsersAndAssignedCourses []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
		}
	}
	lockGetUser                    sync.RWMutex
	lockGetUsersAndAssignedCourses sync.RWMutex
}

// GetUser calls GetUserFunc.
func (mock *UserRepositoryMock) GetUser(contextMoqParam context.Context, s string) (*domain.User, error) {
	if mock.GetUserFunc == nil {
		panic("UserRepositoryMock.GetUserFunc: method is nil but UserRepository.GetUser was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		S               string
	}{
		ContextMoqParam: contextMoqParam,
		S:               s,
	}
	mock.lockGetUser.Lock()
	mock.calls.GetUser = append(mock.calls.GetUser, callInfo)
	mock.lockGetUser.Unlock()
	return mock.GetUserFunc(contextMoqParam, s)
}

// GetUserCalls gets all the calls that were made to GetUser.
// Check the length with:
//
//	len(mockedUserRepository.GetUserCalls())
func (mock *UserRepositoryMock) GetUserCalls() []struct {
	ContextMoqParam context.Context
	S               string
} {
	var calls []struct {
		ContextMoqParam context.Context
		S               string
	}
	mock.lockGetUser.RLock()
	calls = mock.calls.GetUser
	mock.lockGetUser.RUnlock()
	return calls
}

// GetUsersAndAssignedCourses calls GetUsersAndAssignedCoursesFunc.
func (mock *UserRepositoryMock) GetUsersAndAssignedCourses(contextMoqParam context.Context) ([]domain.UserWithAssignedCourses, error) {
	if mock.GetUsersAndAssignedCoursesFunc == nil {
		panic("UserRepositoryMock.GetUsersAndAssignedCoursesFunc: method is nil but UserRepository.GetUsersAndAssignedCourses was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
	}{
		ContextMoqParam: contextMoqParam,
	}
	mock.lockGetUsersAndAssignedCourses.Lock()
	mock.calls.GetUsersAndAssignedCourses = append(mock.calls.GetUsersAndAssignedCourses, callInfo)
	mock.lockGetUsersAndAssignedCourses.Unlock()
	return mock.GetUsersAndAssignedCoursesFunc(contextMoqParam)
}

// GetUsersAndAssignedCoursesCalls gets all the calls that were made to GetUsersAndAssignedCourses.
// Check the length with:
//
//	len(mockedUserRepository.GetUsersAndAssignedCoursesCalls())
func (mock *UserRepositoryMock) GetUsersAndAssignedCoursesCalls() []struct {
	ContextMoqParam context.Context
} {
	var calls []struct {
		ContextMoqParam context.Context
	}
	mock.lockGetUsersAndAssignedCourses.RLock()
	calls = mock.calls.GetUsersAndAssignedCourses
	mock.lockGetUsersAndAssignedCourses.RUnlock()
	return calls
}
