// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/supanova-rp/supanova-server/internal/middleware"
	"github.com/supanova-rp/supanova-server/internal/services/auth"
	"sync"
)

// Ensure, that AuthProviderMock does implement middleware.AuthProvider.
// If this is not the case, regenerate this file with moq.
var _ middleware.AuthProvider = &AuthProviderMock{}

// AuthProviderMock is a mock implementation of middleware.AuthProvider.
//
//	func TestSomethingThatUsesAuthProvider(t *testing.T) {
//
//		// make and configure a mocked middleware.AuthProvider
//		mockedAuthProvider := &AuthProviderMock{
//			GetUserFromIDTokenFunc: func(ctx context.Context, token string) (*auth.User, error) {
//				panic("mock out the GetUserFromIDToken method")
//			},
//		}
//
//		// use mockedAuthProvider in code that requires middleware.AuthProvider
//		// and then make assertions.
//
//	}
type AuthProviderMock struct {
	// GetUserFromIDTokenFunc mocks the GetUserFromIDToken method.
	GetUserFromIDTokenFunc func(ctx context.Context, token string) (*auth.User, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetUserFromIDToken holds details about calls to the GetUserFromIDToken method.
		GetUserFromIDToken []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Token is the token argument value.
			Token string
		}
	}
	lockGetUserFromIDToken sync.RWMutex
}

// GetUserFromIDToken calls GetUserFromIDTokenFunc.
func (mock *AuthProviderMock) GetUserFromIDToken(ctx context.Context, token string) (*auth.User, error) {
	if mock.GetUserFromIDTokenFunc == nil {
		panic("AuthProviderMock.GetUserFromIDTokenFunc: method is nil but AuthProvider.GetUserFromIDToken was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Token string
	}{
		Ctx:   ctx,
		Token: token,
	}
	mock.lockGetUserFromIDToken.Lock()
	mock.calls.GetUserFromIDToken = append(mock.calls.GetUserFromIDToken, callInfo)
	mock.lockGetUserFromIDToken.Unlock()
	return mock.GetUserFromIDTokenFunc(ctx, token)
}

// GetUserFromIDTokenCalls gets all the calls that were made to GetUserFromIDToken.
// Check the length with:
//
//	len(mockedAuthProvider.GetUserFromIDTokenCalls())
func (mock *AuthProviderMock) GetUserFromIDTokenCalls() []struct {
	Ctx   context.Context
	Token string
} {
	var calls []struct {
		Ctx   context.Context
		Token string
	}
	mock.lockGetUserFromIDToken.RLock()
	calls = mock.calls.GetUserFromIDToken
	mock.lockGetUserFromIDToken.RUnlock()
	return calls
}
