// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/supanova-rp/supanova-server/internal/middleware"
	"github.com/supanova-rp/supanova-server/internal/services/auth"
	"sync"
)

// Ensure, that AuthMock does implement middleware.Auth.
// If this is not the case, regenerate this file with moq.
var _ middleware.Auth = &AuthMock{}

// AuthMock is a mock implementation of middleware.Auth.
//
//	func TestSomethingThatUsesAuth(t *testing.T) {
//
//		// make and configure a mocked middleware.Auth
//		mockedAuth := &AuthMock{
//			GetUserFromIDTokenFunc: func(ctx context.Context, token string) (*auth.User, error) {
//				panic("mock out the GetUserFromIDToken method")
//			},
//		}
//
//		// use mockedAuth in code that requires middleware.Auth
//		// and then make assertions.
//
//	}
type AuthMock struct {
	// GetUserFromIDTokenFunc mocks the GetUserFromIDToken method.
	GetUserFromIDTokenFunc func(ctx context.Context, token string) (*auth.User, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetUserFromIDToken holds details about calls to the GetUserFromIDToken method.
		GetUserFromIDToken []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Token is the token argument value.
			Token string
		}
	}
	lockGetUserFromIDToken sync.RWMutex
}

// GetUserFromIDToken calls GetUserFromIDTokenFunc.
func (mock *AuthMock) GetUserFromIDToken(ctx context.Context, token string) (*auth.User, error) {
	if mock.GetUserFromIDTokenFunc == nil {
		panic("AuthMock.GetUserFromIDTokenFunc: method is nil but Auth.GetUserFromIDToken was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Token string
	}{
		Ctx:   ctx,
		Token: token,
	}
	mock.lockGetUserFromIDToken.Lock()
	mock.calls.GetUserFromIDToken = append(mock.calls.GetUserFromIDToken, callInfo)
	mock.lockGetUserFromIDToken.Unlock()
	return mock.GetUserFromIDTokenFunc(ctx, token)
}

// GetUserFromIDTokenCalls gets all the calls that were made to GetUserFromIDToken.
// Check the length with:
//
//	len(mockedAuth.GetUserFromIDTokenCalls())
func (mock *AuthMock) GetUserFromIDTokenCalls() []struct {
	Ctx   context.Context
	Token string
} {
	var calls []struct {
		Ctx   context.Context
		Token string
	}
	mock.lockGetUserFromIDToken.RLock()
	calls = mock.calls.GetUserFromIDToken
	mock.lockGetUserFromIDToken.RUnlock()
	return calls
}
